/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetUserListRequest } from './RpcGetUserListRequest';
import {
    RpcGetUserListRequestFromJSON,
    RpcGetUserListRequestFromJSONTyped,
    RpcGetUserListRequestToJSON,
    RpcGetUserListRequestToJSONTyped,
} from './RpcGetUserListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetUserListMethod
 */
export interface RequestBodyOfTheGetUserListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetUserListMethod
     */
    jsonrpc?: RequestBodyOfTheGetUserListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserListMethod
     */
    method?: RequestBodyOfTheGetUserListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetUserListRequest}
     * @memberof RequestBodyOfTheGetUserListMethod
     */
    params?: RpcGetUserListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetUserListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetUserListMethodJsonrpcEnum = typeof RequestBodyOfTheGetUserListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetUserListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetUserListMethodMethodEnum = {
    GetUserList: 'get_user_list'
} as const;
export type RequestBodyOfTheGetUserListMethodMethodEnum = typeof RequestBodyOfTheGetUserListMethodMethodEnum[keyof typeof RequestBodyOfTheGetUserListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetUserListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetUserListMethod(value: object): value is RequestBodyOfTheGetUserListMethod {
    return true;
}

export function RequestBodyOfTheGetUserListMethodFromJSON(json: any): RequestBodyOfTheGetUserListMethod {
    return RequestBodyOfTheGetUserListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetUserListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetUserListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetUserListMethodToJSON(json: any): RequestBodyOfTheGetUserListMethod {
    return RequestBodyOfTheGetUserListMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserListMethodToJSONTyped(value?: RequestBodyOfTheGetUserListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetUserListRequestToJSON(value['params']),
    };
}

