/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetSubmissionSnippetListRequest } from './RpcGetSubmissionSnippetListRequest';
import {
    RpcGetSubmissionSnippetListRequestFromJSON,
    RpcGetSubmissionSnippetListRequestFromJSONTyped,
    RpcGetSubmissionSnippetListRequestToJSON,
    RpcGetSubmissionSnippetListRequestToJSONTyped,
} from './RpcGetSubmissionSnippetListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetSubmissionSnippetListMethod
 */
export interface RequestBodyOfTheGetSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    jsonrpc?: RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    method?: RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetSubmissionSnippetListRequest}
     * @memberof RequestBodyOfTheGetSubmissionSnippetListMethod
     */
    params?: RpcGetSubmissionSnippetListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum = typeof RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetSubmissionSnippetListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum = {
    GetSubmissionSnippetList: 'get_submission_snippet_list'
} as const;
export type RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum = typeof RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum[keyof typeof RequestBodyOfTheGetSubmissionSnippetListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetSubmissionSnippetListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetSubmissionSnippetListMethod(value: object): value is RequestBodyOfTheGetSubmissionSnippetListMethod {
    return true;
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodFromJSON(json: any): RequestBodyOfTheGetSubmissionSnippetListMethod {
    return RequestBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetSubmissionSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetSubmissionSnippetListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodToJSON(json: any): RequestBodyOfTheGetSubmissionSnippetListMethod {
    return RequestBodyOfTheGetSubmissionSnippetListMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetSubmissionSnippetListMethodToJSONTyped(value?: RequestBodyOfTheGetSubmissionSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetSubmissionSnippetListRequestToJSON(value['params']),
    };
}

