/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateSubmissionRequest } from './RpcCreateSubmissionRequest';
import {
    RpcCreateSubmissionRequestFromJSON,
    RpcCreateSubmissionRequestFromJSONTyped,
    RpcCreateSubmissionRequestToJSON,
    RpcCreateSubmissionRequestToJSONTyped,
} from './RpcCreateSubmissionRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateSubmissionMethod
 */
export interface RequestBodyOfTheCreateSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateSubmissionMethod
     */
    jsonrpc?: RequestBodyOfTheCreateSubmissionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateSubmissionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateSubmissionMethod
     */
    method?: RequestBodyOfTheCreateSubmissionMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateSubmissionRequest}
     * @memberof RequestBodyOfTheCreateSubmissionMethod
     */
    params?: RpcCreateSubmissionRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateSubmissionMethodJsonrpcEnum = typeof RequestBodyOfTheCreateSubmissionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateSubmissionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateSubmissionMethodMethodEnum = {
    CreateSubmission: 'create_submission'
} as const;
export type RequestBodyOfTheCreateSubmissionMethodMethodEnum = typeof RequestBodyOfTheCreateSubmissionMethodMethodEnum[keyof typeof RequestBodyOfTheCreateSubmissionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateSubmissionMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateSubmissionMethod(value: object): value is RequestBodyOfTheCreateSubmissionMethod {
    return true;
}

export function RequestBodyOfTheCreateSubmissionMethodFromJSON(json: any): RequestBodyOfTheCreateSubmissionMethod {
    return RequestBodyOfTheCreateSubmissionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcCreateSubmissionRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateSubmissionMethodToJSON(json: any): RequestBodyOfTheCreateSubmissionMethod {
    return RequestBodyOfTheCreateSubmissionMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheCreateSubmissionMethodToJSONTyped(value?: RequestBodyOfTheCreateSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcCreateSubmissionRequestToJSON(value['params']),
    };
}

