/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetProblemTestCaseSnippetListRequest } from './RpcGetProblemTestCaseSnippetListRequest';
import {
    RpcGetProblemTestCaseSnippetListRequestFromJSON,
    RpcGetProblemTestCaseSnippetListRequestFromJSONTyped,
    RpcGetProblemTestCaseSnippetListRequestToJSON,
    RpcGetProblemTestCaseSnippetListRequestToJSONTyped,
} from './RpcGetProblemTestCaseSnippetListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetProblemTestCaseSnippetListMethod
 */
export interface RequestBodyOfTheGetProblemTestCaseSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    jsonrpc?: RequestBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    method?: RequestBodyOfTheGetProblemTestCaseSnippetListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetProblemTestCaseSnippetListRequest}
     * @memberof RequestBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    params?: RpcGetProblemTestCaseSnippetListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum = typeof RequestBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetProblemTestCaseSnippetListMethodMethodEnum = {
    GetProblemTestCaseSnippetList: 'get_problem_test_case_snippet_list'
} as const;
export type RequestBodyOfTheGetProblemTestCaseSnippetListMethodMethodEnum = typeof RequestBodyOfTheGetProblemTestCaseSnippetListMethodMethodEnum[keyof typeof RequestBodyOfTheGetProblemTestCaseSnippetListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetProblemTestCaseSnippetListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetProblemTestCaseSnippetListMethod(value: object): value is RequestBodyOfTheGetProblemTestCaseSnippetListMethod {
    return true;
}

export function RequestBodyOfTheGetProblemTestCaseSnippetListMethodFromJSON(json: any): RequestBodyOfTheGetProblemTestCaseSnippetListMethod {
    return RequestBodyOfTheGetProblemTestCaseSnippetListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetProblemTestCaseSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetProblemTestCaseSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetProblemTestCaseSnippetListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetProblemTestCaseSnippetListMethodToJSON(json: any): RequestBodyOfTheGetProblemTestCaseSnippetListMethod {
    return RequestBodyOfTheGetProblemTestCaseSnippetListMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetProblemTestCaseSnippetListMethodToJSONTyped(value?: RequestBodyOfTheGetProblemTestCaseSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetProblemTestCaseSnippetListRequestToJSON(value['params']),
    };
}

