/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateSessionRequest } from './RpcCreateSessionRequest';
import {
    RpcCreateSessionRequestFromJSON,
    RpcCreateSessionRequestFromJSONTyped,
    RpcCreateSessionRequestToJSON,
    RpcCreateSessionRequestToJSONTyped,
} from './RpcCreateSessionRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateSessionMethod
 */
export interface RequestBodyOfTheCreateSessionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateSessionMethod
     */
    jsonrpc?: RequestBodyOfTheCreateSessionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateSessionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateSessionMethod
     */
    method?: RequestBodyOfTheCreateSessionMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateSessionRequest}
     * @memberof RequestBodyOfTheCreateSessionMethod
     */
    params?: RpcCreateSessionRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateSessionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateSessionMethodJsonrpcEnum = typeof RequestBodyOfTheCreateSessionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateSessionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateSessionMethodMethodEnum = {
    CreateSession: 'create_session'
} as const;
export type RequestBodyOfTheCreateSessionMethodMethodEnum = typeof RequestBodyOfTheCreateSessionMethodMethodEnum[keyof typeof RequestBodyOfTheCreateSessionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateSessionMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateSessionMethod(value: object): value is RequestBodyOfTheCreateSessionMethod {
    return true;
}

export function RequestBodyOfTheCreateSessionMethodFromJSON(json: any): RequestBodyOfTheCreateSessionMethod {
    return RequestBodyOfTheCreateSessionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateSessionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateSessionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcCreateSessionRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateSessionMethodToJSON(json: any): RequestBodyOfTheCreateSessionMethod {
    return RequestBodyOfTheCreateSessionMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheCreateSessionMethodToJSONTyped(value?: RequestBodyOfTheCreateSessionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcCreateSessionRequestToJSON(value['params']),
    };
}

