/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateAccountRequest } from './RpcCreateAccountRequest';
import {
    RpcCreateAccountRequestFromJSON,
    RpcCreateAccountRequestFromJSONTyped,
    RpcCreateAccountRequestToJSON,
    RpcCreateAccountRequestToJSONTyped,
} from './RpcCreateAccountRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateAccountMethod
 */
export interface RequestBodyOfTheCreateAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateAccountMethod
     */
    jsonrpc?: RequestBodyOfTheCreateAccountMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateAccountMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateAccountMethod
     */
    method?: RequestBodyOfTheCreateAccountMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateAccountRequest}
     * @memberof RequestBodyOfTheCreateAccountMethod
     */
    params?: RpcCreateAccountRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateAccountMethodJsonrpcEnum = typeof RequestBodyOfTheCreateAccountMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateAccountMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateAccountMethodMethodEnum = {
    CreateAccount: 'create_account'
} as const;
export type RequestBodyOfTheCreateAccountMethodMethodEnum = typeof RequestBodyOfTheCreateAccountMethodMethodEnum[keyof typeof RequestBodyOfTheCreateAccountMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateAccountMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateAccountMethod(value: object): value is RequestBodyOfTheCreateAccountMethod {
    return true;
}

export function RequestBodyOfTheCreateAccountMethodFromJSON(json: any): RequestBodyOfTheCreateAccountMethod {
    return RequestBodyOfTheCreateAccountMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcCreateAccountRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateAccountMethodToJSON(json: any): RequestBodyOfTheCreateAccountMethod {
    return RequestBodyOfTheCreateAccountMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheCreateAccountMethodToJSONTyped(value?: RequestBodyOfTheCreateAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcCreateAccountRequestToJSON(value['params']),
    };
}

