/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUpdateAccountRequest } from './RpcUpdateAccountRequest';
import {
    RpcUpdateAccountRequestFromJSON,
    RpcUpdateAccountRequestFromJSONTyped,
    RpcUpdateAccountRequestToJSON,
    RpcUpdateAccountRequestToJSONTyped,
} from './RpcUpdateAccountRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheUpdateAccountMethod
 */
export interface RequestBodyOfTheUpdateAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheUpdateAccountMethod
     */
    jsonrpc?: RequestBodyOfTheUpdateAccountMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateAccountMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheUpdateAccountMethod
     */
    method?: RequestBodyOfTheUpdateAccountMethodMethodEnum;
    /**
     * 
     * @type {RpcUpdateAccountRequest}
     * @memberof RequestBodyOfTheUpdateAccountMethod
     */
    params?: RpcUpdateAccountRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheUpdateAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheUpdateAccountMethodJsonrpcEnum = typeof RequestBodyOfTheUpdateAccountMethodJsonrpcEnum[keyof typeof RequestBodyOfTheUpdateAccountMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheUpdateAccountMethodMethodEnum = {
    UpdateAccount: 'update_account'
} as const;
export type RequestBodyOfTheUpdateAccountMethodMethodEnum = typeof RequestBodyOfTheUpdateAccountMethodMethodEnum[keyof typeof RequestBodyOfTheUpdateAccountMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheUpdateAccountMethod interface.
 */
export function instanceOfRequestBodyOfTheUpdateAccountMethod(value: object): value is RequestBodyOfTheUpdateAccountMethod {
    return true;
}

export function RequestBodyOfTheUpdateAccountMethodFromJSON(json: any): RequestBodyOfTheUpdateAccountMethod {
    return RequestBodyOfTheUpdateAccountMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheUpdateAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheUpdateAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcUpdateAccountRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheUpdateAccountMethodToJSON(json: any): RequestBodyOfTheUpdateAccountMethod {
    return RequestBodyOfTheUpdateAccountMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheUpdateAccountMethodToJSONTyped(value?: RequestBodyOfTheUpdateAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcUpdateAccountRequestToJSON(value['params']),
    };
}

