/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcDeleteTestCaseRequest } from './RpcDeleteTestCaseRequest';
import {
    RpcDeleteTestCaseRequestFromJSON,
    RpcDeleteTestCaseRequestFromJSONTyped,
    RpcDeleteTestCaseRequestToJSON,
    RpcDeleteTestCaseRequestToJSONTyped,
} from './RpcDeleteTestCaseRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheDeleteTestCaseMethod
 */
export interface RequestBodyOfTheDeleteTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheDeleteTestCaseMethod
     */
    jsonrpc?: RequestBodyOfTheDeleteTestCaseMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteTestCaseMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteTestCaseMethod
     */
    method?: RequestBodyOfTheDeleteTestCaseMethodMethodEnum;
    /**
     * 
     * @type {RpcDeleteTestCaseRequest}
     * @memberof RequestBodyOfTheDeleteTestCaseMethod
     */
    params?: RpcDeleteTestCaseRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheDeleteTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheDeleteTestCaseMethodJsonrpcEnum = typeof RequestBodyOfTheDeleteTestCaseMethodJsonrpcEnum[keyof typeof RequestBodyOfTheDeleteTestCaseMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheDeleteTestCaseMethodMethodEnum = {
    DeleteTestCase: 'delete_test_case'
} as const;
export type RequestBodyOfTheDeleteTestCaseMethodMethodEnum = typeof RequestBodyOfTheDeleteTestCaseMethodMethodEnum[keyof typeof RequestBodyOfTheDeleteTestCaseMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheDeleteTestCaseMethod interface.
 */
export function instanceOfRequestBodyOfTheDeleteTestCaseMethod(value: object): value is RequestBodyOfTheDeleteTestCaseMethod {
    return true;
}

export function RequestBodyOfTheDeleteTestCaseMethodFromJSON(json: any): RequestBodyOfTheDeleteTestCaseMethod {
    return RequestBodyOfTheDeleteTestCaseMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheDeleteTestCaseMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcDeleteTestCaseRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheDeleteTestCaseMethodToJSON(json: any): RequestBodyOfTheDeleteTestCaseMethod {
    return RequestBodyOfTheDeleteTestCaseMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteTestCaseMethodToJSONTyped(value?: RequestBodyOfTheDeleteTestCaseMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcDeleteTestCaseRequestToJSON(value['params']),
    };
}

