/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetUserRequest } from './RpcGetUserRequest';
import {
    RpcGetUserRequestFromJSON,
    RpcGetUserRequestFromJSONTyped,
    RpcGetUserRequestToJSON,
    RpcGetUserRequestToJSONTyped,
} from './RpcGetUserRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetUserMethod
 */
export interface RequestBodyOfTheGetUserMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    jsonrpc?: RequestBodyOfTheGetUserMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    method?: RequestBodyOfTheGetUserMethodMethodEnum;
    /**
     * 
     * @type {RpcGetUserRequest}
     * @memberof RequestBodyOfTheGetUserMethod
     */
    params?: RpcGetUserRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetUserMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetUserMethodJsonrpcEnum = typeof RequestBodyOfTheGetUserMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetUserMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetUserMethodMethodEnum = {
    GetUser: 'get_user'
} as const;
export type RequestBodyOfTheGetUserMethodMethodEnum = typeof RequestBodyOfTheGetUserMethodMethodEnum[keyof typeof RequestBodyOfTheGetUserMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetUserMethod interface.
 */
export function instanceOfRequestBodyOfTheGetUserMethod(value: object): value is RequestBodyOfTheGetUserMethod {
    return true;
}

export function RequestBodyOfTheGetUserMethodFromJSON(json: any): RequestBodyOfTheGetUserMethod {
    return RequestBodyOfTheGetUserMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetUserMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetUserRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetUserMethodToJSON(json: any): RequestBodyOfTheGetUserMethod {
    return RequestBodyOfTheGetUserMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetUserMethodToJSONTyped(value?: RequestBodyOfTheGetUserMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetUserRequestToJSON(value['params']),
    };
}

