/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetAccountRequest } from './RpcGetAccountRequest';
import {
    RpcGetAccountRequestFromJSON,
    RpcGetAccountRequestFromJSONTyped,
    RpcGetAccountRequestToJSON,
    RpcGetAccountRequestToJSONTyped,
} from './RpcGetAccountRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetAccountMethod
 */
export interface RequestBodyOfTheGetAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    jsonrpc?: RequestBodyOfTheGetAccountMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    method?: RequestBodyOfTheGetAccountMethodMethodEnum;
    /**
     * 
     * @type {RpcGetAccountRequest}
     * @memberof RequestBodyOfTheGetAccountMethod
     */
    params?: RpcGetAccountRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetAccountMethodJsonrpcEnum = typeof RequestBodyOfTheGetAccountMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetAccountMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetAccountMethodMethodEnum = {
    GetAccount: 'get_account'
} as const;
export type RequestBodyOfTheGetAccountMethodMethodEnum = typeof RequestBodyOfTheGetAccountMethodMethodEnum[keyof typeof RequestBodyOfTheGetAccountMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetAccountMethod interface.
 */
export function instanceOfRequestBodyOfTheGetAccountMethod(value: object): value is RequestBodyOfTheGetAccountMethod {
    return true;
}

export function RequestBodyOfTheGetAccountMethodFromJSON(json: any): RequestBodyOfTheGetAccountMethod {
    return RequestBodyOfTheGetAccountMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetAccountRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetAccountMethodToJSON(json: any): RequestBodyOfTheGetAccountMethod {
    return RequestBodyOfTheGetAccountMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountMethodToJSONTyped(value?: RequestBodyOfTheGetAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetAccountRequestToJSON(value['params']),
    };
}

