/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcDeleteProblemRequest } from './RpcDeleteProblemRequest';
import {
    RpcDeleteProblemRequestFromJSON,
    RpcDeleteProblemRequestFromJSONTyped,
    RpcDeleteProblemRequestToJSON,
    RpcDeleteProblemRequestToJSONTyped,
} from './RpcDeleteProblemRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheDeleteProblemMethod
 */
export interface RequestBodyOfTheDeleteProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheDeleteProblemMethod
     */
    jsonrpc?: RequestBodyOfTheDeleteProblemMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteProblemMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteProblemMethod
     */
    method?: RequestBodyOfTheDeleteProblemMethodMethodEnum;
    /**
     * 
     * @type {RpcDeleteProblemRequest}
     * @memberof RequestBodyOfTheDeleteProblemMethod
     */
    params?: RpcDeleteProblemRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheDeleteProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheDeleteProblemMethodJsonrpcEnum = typeof RequestBodyOfTheDeleteProblemMethodJsonrpcEnum[keyof typeof RequestBodyOfTheDeleteProblemMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheDeleteProblemMethodMethodEnum = {
    DeleteProblem: 'delete_problem'
} as const;
export type RequestBodyOfTheDeleteProblemMethodMethodEnum = typeof RequestBodyOfTheDeleteProblemMethodMethodEnum[keyof typeof RequestBodyOfTheDeleteProblemMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheDeleteProblemMethod interface.
 */
export function instanceOfRequestBodyOfTheDeleteProblemMethod(value: object): value is RequestBodyOfTheDeleteProblemMethod {
    return true;
}

export function RequestBodyOfTheDeleteProblemMethodFromJSON(json: any): RequestBodyOfTheDeleteProblemMethod {
    return RequestBodyOfTheDeleteProblemMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheDeleteProblemMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcDeleteProblemRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheDeleteProblemMethodToJSON(json: any): RequestBodyOfTheDeleteProblemMethod {
    return RequestBodyOfTheDeleteProblemMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteProblemMethodToJSONTyped(value?: RequestBodyOfTheDeleteProblemMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcDeleteProblemRequestToJSON(value['params']),
    };
}

