/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcDeleteSubmissionRequest } from './RpcDeleteSubmissionRequest';
import {
    RpcDeleteSubmissionRequestFromJSON,
    RpcDeleteSubmissionRequestFromJSONTyped,
    RpcDeleteSubmissionRequestToJSON,
    RpcDeleteSubmissionRequestToJSONTyped,
} from './RpcDeleteSubmissionRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheDeleteSubmissionMethod
 */
export interface RequestBodyOfTheDeleteSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSubmissionMethod
     */
    jsonrpc?: RequestBodyOfTheDeleteSubmissionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSubmissionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheDeleteSubmissionMethod
     */
    method?: RequestBodyOfTheDeleteSubmissionMethodMethodEnum;
    /**
     * 
     * @type {RpcDeleteSubmissionRequest}
     * @memberof RequestBodyOfTheDeleteSubmissionMethod
     */
    params?: RpcDeleteSubmissionRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheDeleteSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheDeleteSubmissionMethodJsonrpcEnum = typeof RequestBodyOfTheDeleteSubmissionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheDeleteSubmissionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheDeleteSubmissionMethodMethodEnum = {
    DeleteSubmission: 'delete_submission'
} as const;
export type RequestBodyOfTheDeleteSubmissionMethodMethodEnum = typeof RequestBodyOfTheDeleteSubmissionMethodMethodEnum[keyof typeof RequestBodyOfTheDeleteSubmissionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheDeleteSubmissionMethod interface.
 */
export function instanceOfRequestBodyOfTheDeleteSubmissionMethod(value: object): value is RequestBodyOfTheDeleteSubmissionMethod {
    return true;
}

export function RequestBodyOfTheDeleteSubmissionMethodFromJSON(json: any): RequestBodyOfTheDeleteSubmissionMethod {
    return RequestBodyOfTheDeleteSubmissionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheDeleteSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcDeleteSubmissionRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheDeleteSubmissionMethodToJSON(json: any): RequestBodyOfTheDeleteSubmissionMethod {
    return RequestBodyOfTheDeleteSubmissionMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheDeleteSubmissionMethodToJSONTyped(value?: RequestBodyOfTheDeleteSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcDeleteSubmissionRequestToJSON(value['params']),
    };
}

