/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetAccountListRequest } from './RpcGetAccountListRequest';
import {
    RpcGetAccountListRequestFromJSON,
    RpcGetAccountListRequestFromJSONTyped,
    RpcGetAccountListRequestToJSON,
    RpcGetAccountListRequestToJSONTyped,
} from './RpcGetAccountListRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetAccountListMethod
 */
export interface RequestBodyOfTheGetAccountListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountListMethod
     */
    jsonrpc?: RequestBodyOfTheGetAccountListMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountListMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetAccountListMethod
     */
    method?: RequestBodyOfTheGetAccountListMethodMethodEnum;
    /**
     * 
     * @type {RpcGetAccountListRequest}
     * @memberof RequestBodyOfTheGetAccountListMethod
     */
    params?: RpcGetAccountListRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetAccountListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetAccountListMethodJsonrpcEnum = typeof RequestBodyOfTheGetAccountListMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetAccountListMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetAccountListMethodMethodEnum = {
    GetAccountList: 'get_account_list'
} as const;
export type RequestBodyOfTheGetAccountListMethodMethodEnum = typeof RequestBodyOfTheGetAccountListMethodMethodEnum[keyof typeof RequestBodyOfTheGetAccountListMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetAccountListMethod interface.
 */
export function instanceOfRequestBodyOfTheGetAccountListMethod(value: object): value is RequestBodyOfTheGetAccountListMethod {
    return true;
}

export function RequestBodyOfTheGetAccountListMethodFromJSON(json: any): RequestBodyOfTheGetAccountListMethod {
    return RequestBodyOfTheGetAccountListMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetAccountListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetAccountListRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetAccountListMethodToJSON(json: any): RequestBodyOfTheGetAccountListMethod {
    return RequestBodyOfTheGetAccountListMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetAccountListMethodToJSONTyped(value?: RequestBodyOfTheGetAccountListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetAccountListRequestToJSON(value['params']),
    };
}

