/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetSubmissionRequest } from './RpcGetSubmissionRequest';
import {
    RpcGetSubmissionRequestFromJSON,
    RpcGetSubmissionRequestFromJSONTyped,
    RpcGetSubmissionRequestToJSON,
    RpcGetSubmissionRequestToJSONTyped,
} from './RpcGetSubmissionRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheGetSubmissionMethod
 */
export interface RequestBodyOfTheGetSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionMethod
     */
    jsonrpc?: RequestBodyOfTheGetSubmissionMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheGetSubmissionMethod
     */
    method?: RequestBodyOfTheGetSubmissionMethodMethodEnum;
    /**
     * 
     * @type {RpcGetSubmissionRequest}
     * @memberof RequestBodyOfTheGetSubmissionMethod
     */
    params?: RpcGetSubmissionRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheGetSubmissionMethodJsonrpcEnum = typeof RequestBodyOfTheGetSubmissionMethodJsonrpcEnum[keyof typeof RequestBodyOfTheGetSubmissionMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheGetSubmissionMethodMethodEnum = {
    GetSubmission: 'get_submission'
} as const;
export type RequestBodyOfTheGetSubmissionMethodMethodEnum = typeof RequestBodyOfTheGetSubmissionMethodMethodEnum[keyof typeof RequestBodyOfTheGetSubmissionMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheGetSubmissionMethod interface.
 */
export function instanceOfRequestBodyOfTheGetSubmissionMethod(value: object): value is RequestBodyOfTheGetSubmissionMethod {
    return true;
}

export function RequestBodyOfTheGetSubmissionMethodFromJSON(json: any): RequestBodyOfTheGetSubmissionMethod {
    return RequestBodyOfTheGetSubmissionMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheGetSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheGetSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcGetSubmissionRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheGetSubmissionMethodToJSON(json: any): RequestBodyOfTheGetSubmissionMethod {
    return RequestBodyOfTheGetSubmissionMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheGetSubmissionMethodToJSONTyped(value?: RequestBodyOfTheGetSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcGetSubmissionRequestToJSON(value['params']),
    };
}

