/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateUserRequest } from './RpcCreateUserRequest';
import {
    RpcCreateUserRequestFromJSON,
    RpcCreateUserRequestFromJSONTyped,
    RpcCreateUserRequestToJSON,
    RpcCreateUserRequestToJSONTyped,
} from './RpcCreateUserRequest';

/**
 * 
 * @export
 * @interface RequestBodyOfTheCreateUserMethod
 */
export interface RequestBodyOfTheCreateUserMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof RequestBodyOfTheCreateUserMethod
     */
    jsonrpc?: RequestBodyOfTheCreateUserMethodJsonrpcEnum;
    /**
     * An identifier established by the Client.
     * @type {string}
     * @memberof RequestBodyOfTheCreateUserMethod
     */
    id?: string;
    /**
     * A String containing the name of the method to be invoked.
     * @type {string}
     * @memberof RequestBodyOfTheCreateUserMethod
     */
    method?: RequestBodyOfTheCreateUserMethodMethodEnum;
    /**
     * 
     * @type {RpcCreateUserRequest}
     * @memberof RequestBodyOfTheCreateUserMethod
     */
    params?: RpcCreateUserRequest;
}


/**
 * @export
 */
export const RequestBodyOfTheCreateUserMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type RequestBodyOfTheCreateUserMethodJsonrpcEnum = typeof RequestBodyOfTheCreateUserMethodJsonrpcEnum[keyof typeof RequestBodyOfTheCreateUserMethodJsonrpcEnum];

/**
 * @export
 */
export const RequestBodyOfTheCreateUserMethodMethodEnum = {
    CreateUser: 'create_user'
} as const;
export type RequestBodyOfTheCreateUserMethodMethodEnum = typeof RequestBodyOfTheCreateUserMethodMethodEnum[keyof typeof RequestBodyOfTheCreateUserMethodMethodEnum];


/**
 * Check if a given object implements the RequestBodyOfTheCreateUserMethod interface.
 */
export function instanceOfRequestBodyOfTheCreateUserMethod(value: object): value is RequestBodyOfTheCreateUserMethod {
    return true;
}

export function RequestBodyOfTheCreateUserMethodFromJSON(json: any): RequestBodyOfTheCreateUserMethod {
    return RequestBodyOfTheCreateUserMethodFromJSONTyped(json, false);
}

export function RequestBodyOfTheCreateUserMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestBodyOfTheCreateUserMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'method': json['method'] == null ? undefined : json['method'],
        'params': json['params'] == null ? undefined : RpcCreateUserRequestFromJSON(json['params']),
    };
}

export function RequestBodyOfTheCreateUserMethodToJSON(json: any): RequestBodyOfTheCreateUserMethod {
    return RequestBodyOfTheCreateUserMethodToJSONTyped(json, false);
}

export function RequestBodyOfTheCreateUserMethodToJSONTyped(value?: RequestBodyOfTheCreateUserMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'method': value['method'],
        'params': RpcCreateUserRequestToJSON(value['params']),
    };
}

