/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetProblemTestCaseSnippetListResponse } from './RpcGetProblemTestCaseSnippetListResponse';
import {
    RpcGetProblemTestCaseSnippetListResponseFromJSON,
    RpcGetProblemTestCaseSnippetListResponseFromJSONTyped,
    RpcGetProblemTestCaseSnippetListResponseToJSON,
    RpcGetProblemTestCaseSnippetListResponseToJSONTyped,
} from './RpcGetProblemTestCaseSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetProblemTestCaseSnippetListMethod
 */
export interface ResponseBodyOfTheGetProblemTestCaseSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetProblemTestCaseSnippetListResponse}
     * @memberof ResponseBodyOfTheGetProblemTestCaseSnippetListMethod
     */
    result?: RpcGetProblemTestCaseSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetProblemTestCaseSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetProblemTestCaseSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetProblemTestCaseSnippetListMethod(value: object): value is ResponseBodyOfTheGetProblemTestCaseSnippetListMethod {
    return true;
}

export function ResponseBodyOfTheGetProblemTestCaseSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetProblemTestCaseSnippetListMethod {
    return ResponseBodyOfTheGetProblemTestCaseSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemTestCaseSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetProblemTestCaseSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetProblemTestCaseSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetProblemTestCaseSnippetListMethodToJSON(json: any): ResponseBodyOfTheGetProblemTestCaseSnippetListMethod {
    return ResponseBodyOfTheGetProblemTestCaseSnippetListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemTestCaseSnippetListMethodToJSONTyped(value?: ResponseBodyOfTheGetProblemTestCaseSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetProblemTestCaseSnippetListResponseToJSON(value['result']),
    };
}

