/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUpdateTestCaseResponse } from './RpcUpdateTestCaseResponse';
import {
    RpcUpdateTestCaseResponseFromJSON,
    RpcUpdateTestCaseResponseFromJSONTyped,
    RpcUpdateTestCaseResponseToJSON,
    RpcUpdateTestCaseResponseToJSONTyped,
} from './RpcUpdateTestCaseResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheUpdateTestCaseMethod
 */
export interface ResponseBodyOfTheUpdateTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    jsonrpc?: ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcUpdateTestCaseResponse}
     * @memberof ResponseBodyOfTheUpdateTestCaseMethod
     */
    result?: RpcUpdateTestCaseResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum = typeof ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheUpdateTestCaseMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheUpdateTestCaseMethod interface.
 */
export function instanceOfResponseBodyOfTheUpdateTestCaseMethod(value: object): value is ResponseBodyOfTheUpdateTestCaseMethod {
    return true;
}

export function ResponseBodyOfTheUpdateTestCaseMethodFromJSON(json: any): ResponseBodyOfTheUpdateTestCaseMethod {
    return ResponseBodyOfTheUpdateTestCaseMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheUpdateTestCaseMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcUpdateTestCaseResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheUpdateTestCaseMethodToJSON(json: any): ResponseBodyOfTheUpdateTestCaseMethod {
    return ResponseBodyOfTheUpdateTestCaseMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateTestCaseMethodToJSONTyped(value?: ResponseBodyOfTheUpdateTestCaseMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcUpdateTestCaseResponseToJSON(value['result']),
    };
}

