/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateProblemResponse } from './RpcCreateProblemResponse';
import {
    RpcCreateProblemResponseFromJSON,
    RpcCreateProblemResponseFromJSONTyped,
    RpcCreateProblemResponseToJSON,
    RpcCreateProblemResponseToJSONTyped,
} from './RpcCreateProblemResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheCreateProblemMethod
 */
export interface ResponseBodyOfTheCreateProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    jsonrpc?: ResponseBodyOfTheCreateProblemMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcCreateProblemResponse}
     * @memberof ResponseBodyOfTheCreateProblemMethod
     */
    result?: RpcCreateProblemResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheCreateProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheCreateProblemMethodJsonrpcEnum = typeof ResponseBodyOfTheCreateProblemMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheCreateProblemMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheCreateProblemMethod interface.
 */
export function instanceOfResponseBodyOfTheCreateProblemMethod(value: object): value is ResponseBodyOfTheCreateProblemMethod {
    return true;
}

export function ResponseBodyOfTheCreateProblemMethodFromJSON(json: any): ResponseBodyOfTheCreateProblemMethod {
    return ResponseBodyOfTheCreateProblemMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheCreateProblemMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcCreateProblemResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheCreateProblemMethodToJSON(json: any): ResponseBodyOfTheCreateProblemMethod {
    return ResponseBodyOfTheCreateProblemMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateProblemMethodToJSONTyped(value?: ResponseBodyOfTheCreateProblemMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcCreateProblemResponseToJSON(value['result']),
    };
}

