/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetTestCaseResponse } from './RpcGetTestCaseResponse';
import {
    RpcGetTestCaseResponseFromJSON,
    RpcGetTestCaseResponseFromJSONTyped,
    RpcGetTestCaseResponseToJSON,
    RpcGetTestCaseResponseToJSONTyped,
} from './RpcGetTestCaseResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetTestCaseMethod
 */
export interface ResponseBodyOfTheGetTestCaseMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    jsonrpc?: ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetTestCaseResponse}
     * @memberof ResponseBodyOfTheGetTestCaseMethod
     */
    result?: RpcGetTestCaseResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum = typeof ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetTestCaseMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetTestCaseMethod interface.
 */
export function instanceOfResponseBodyOfTheGetTestCaseMethod(value: object): value is ResponseBodyOfTheGetTestCaseMethod {
    return true;
}

export function ResponseBodyOfTheGetTestCaseMethodFromJSON(json: any): ResponseBodyOfTheGetTestCaseMethod {
    return ResponseBodyOfTheGetTestCaseMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetTestCaseMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetTestCaseMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetTestCaseResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetTestCaseMethodToJSON(json: any): ResponseBodyOfTheGetTestCaseMethod {
    return ResponseBodyOfTheGetTestCaseMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetTestCaseMethodToJSONTyped(value?: ResponseBodyOfTheGetTestCaseMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetTestCaseResponseToJSON(value['result']),
    };
}

