/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheDeleteProblemMethod
 */
export interface ResponseBodyOfTheDeleteProblemMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteProblemMethod
     */
    jsonrpc?: ResponseBodyOfTheDeleteProblemMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteProblemMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheDeleteProblemMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {object}
     * @memberof ResponseBodyOfTheDeleteProblemMethod
     */
    result?: object;
}


/**
 * @export
 */
export const ResponseBodyOfTheDeleteProblemMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheDeleteProblemMethodJsonrpcEnum = typeof ResponseBodyOfTheDeleteProblemMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheDeleteProblemMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheDeleteProblemMethod interface.
 */
export function instanceOfResponseBodyOfTheDeleteProblemMethod(value: object): value is ResponseBodyOfTheDeleteProblemMethod {
    return true;
}

export function ResponseBodyOfTheDeleteProblemMethodFromJSON(json: any): ResponseBodyOfTheDeleteProblemMethod {
    return ResponseBodyOfTheDeleteProblemMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteProblemMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheDeleteProblemMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function ResponseBodyOfTheDeleteProblemMethodToJSON(json: any): ResponseBodyOfTheDeleteProblemMethod {
    return ResponseBodyOfTheDeleteProblemMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteProblemMethodToJSONTyped(value?: ResponseBodyOfTheDeleteProblemMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': value['result'],
    };
}

