/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetAccountProblemSnippetListResponse } from './RpcGetAccountProblemSnippetListResponse';
import {
    RpcGetAccountProblemSnippetListResponseFromJSON,
    RpcGetAccountProblemSnippetListResponseFromJSONTyped,
    RpcGetAccountProblemSnippetListResponseToJSON,
    RpcGetAccountProblemSnippetListResponseToJSONTyped,
} from './RpcGetAccountProblemSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountProblemSnippetListMethod
 */
export interface ResponseBodyOfTheGetAccountProblemSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountProblemSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountProblemSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountProblemSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountProblemSnippetListResponse}
     * @memberof ResponseBodyOfTheGetAccountProblemSnippetListMethod
     */
    result?: RpcGetAccountProblemSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountProblemSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountProblemSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountProblemSnippetListMethod(value: object): value is ResponseBodyOfTheGetAccountProblemSnippetListMethod {
    return true;
}

export function ResponseBodyOfTheGetAccountProblemSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetAccountProblemSnippetListMethod {
    return ResponseBodyOfTheGetAccountProblemSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountProblemSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountProblemSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetAccountProblemSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountProblemSnippetListMethodToJSON(json: any): ResponseBodyOfTheGetAccountProblemSnippetListMethod {
    return ResponseBodyOfTheGetAccountProblemSnippetListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountProblemSnippetListMethodToJSONTyped(value?: ResponseBodyOfTheGetAccountProblemSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetAccountProblemSnippetListResponseToJSON(value['result']),
    };
}

