/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateSubmissionResponse } from './RpcCreateSubmissionResponse';
import {
    RpcCreateSubmissionResponseFromJSON,
    RpcCreateSubmissionResponseFromJSONTyped,
    RpcCreateSubmissionResponseToJSON,
    RpcCreateSubmissionResponseToJSONTyped,
} from './RpcCreateSubmissionResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheCreateSubmissionMethod
 */
export interface ResponseBodyOfTheCreateSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheCreateSubmissionMethod
     */
    jsonrpc?: ResponseBodyOfTheCreateSubmissionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheCreateSubmissionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheCreateSubmissionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcCreateSubmissionResponse}
     * @memberof ResponseBodyOfTheCreateSubmissionMethod
     */
    result?: RpcCreateSubmissionResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheCreateSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheCreateSubmissionMethodJsonrpcEnum = typeof ResponseBodyOfTheCreateSubmissionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheCreateSubmissionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheCreateSubmissionMethod interface.
 */
export function instanceOfResponseBodyOfTheCreateSubmissionMethod(value: object): value is ResponseBodyOfTheCreateSubmissionMethod {
    return true;
}

export function ResponseBodyOfTheCreateSubmissionMethodFromJSON(json: any): ResponseBodyOfTheCreateSubmissionMethod {
    return ResponseBodyOfTheCreateSubmissionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheCreateSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcCreateSubmissionResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheCreateSubmissionMethodToJSON(json: any): ResponseBodyOfTheCreateSubmissionMethod {
    return ResponseBodyOfTheCreateSubmissionMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateSubmissionMethodToJSONTyped(value?: ResponseBodyOfTheCreateSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcCreateSubmissionResponseToJSON(value['result']),
    };
}

