/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetAccountListResponse } from './RpcGetAccountListResponse';
import {
    RpcGetAccountListResponseFromJSON,
    RpcGetAccountListResponseFromJSONTyped,
    RpcGetAccountListResponseToJSON,
    RpcGetAccountListResponseToJSONTyped,
} from './RpcGetAccountListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountListMethod
 */
export interface ResponseBodyOfTheGetAccountListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountListResponse}
     * @memberof ResponseBodyOfTheGetAccountListMethod
     */
    result?: RpcGetAccountListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountListMethod(value: object): value is ResponseBodyOfTheGetAccountListMethod {
    return true;
}

export function ResponseBodyOfTheGetAccountListMethodFromJSON(json: any): ResponseBodyOfTheGetAccountListMethod {
    return ResponseBodyOfTheGetAccountListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetAccountListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountListMethodToJSON(json: any): ResponseBodyOfTheGetAccountListMethod {
    return ResponseBodyOfTheGetAccountListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountListMethodToJSONTyped(value?: ResponseBodyOfTheGetAccountListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetAccountListResponseToJSON(value['result']),
    };
}

