/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetUserSubmissionSnippetListResponse } from './RpcGetUserSubmissionSnippetListResponse';
import {
    RpcGetUserSubmissionSnippetListResponseFromJSON,
    RpcGetUserSubmissionSnippetListResponseFromJSONTyped,
    RpcGetUserSubmissionSnippetListResponseToJSON,
    RpcGetUserSubmissionSnippetListResponseToJSONTyped,
} from './RpcGetUserSubmissionSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetUserSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetUserSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetUserSubmissionSnippetListMethod
     */
    result?: RpcGetUserSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetUserSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetUserSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetUserSubmissionSnippetListMethod(value: object): value is ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    return true;
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetUserSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodToJSON(json: any): ResponseBodyOfTheGetUserSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetUserSubmissionSnippetListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserSubmissionSnippetListMethodToJSONTyped(value?: ResponseBodyOfTheGetUserSubmissionSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetUserSubmissionSnippetListResponseToJSON(value['result']),
    };
}

