/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetAccountResponse } from './RpcGetAccountResponse';
import {
    RpcGetAccountResponseFromJSON,
    RpcGetAccountResponseFromJSONTyped,
    RpcGetAccountResponseToJSON,
    RpcGetAccountResponseToJSONTyped,
} from './RpcGetAccountResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountMethod
 */
export interface ResponseBodyOfTheGetAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountResponse}
     * @memberof ResponseBodyOfTheGetAccountMethod
     */
    result?: RpcGetAccountResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountMethod(value: object): value is ResponseBodyOfTheGetAccountMethod {
    return true;
}

export function ResponseBodyOfTheGetAccountMethodFromJSON(json: any): ResponseBodyOfTheGetAccountMethod {
    return ResponseBodyOfTheGetAccountMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetAccountResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountMethodToJSON(json: any): ResponseBodyOfTheGetAccountMethod {
    return ResponseBodyOfTheGetAccountMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountMethodToJSONTyped(value?: ResponseBodyOfTheGetAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetAccountResponseToJSON(value['result']),
    };
}

