/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcGetAccountSubmissionSnippetListResponse } from './RpcGetAccountSubmissionSnippetListResponse';
import {
    RpcGetAccountSubmissionSnippetListResponseFromJSON,
    RpcGetAccountSubmissionSnippetListResponseFromJSONTyped,
    RpcGetAccountSubmissionSnippetListResponseToJSON,
    RpcGetAccountSubmissionSnippetListResponseToJSONTyped,
} from './RpcGetAccountSubmissionSnippetListResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetAccountSubmissionSnippetListMethod
 */
export interface ResponseBodyOfTheGetAccountSubmissionSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountSubmissionSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetAccountSubmissionSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetAccountSubmissionSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetAccountSubmissionSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetAccountSubmissionSnippetListResponse}
     * @memberof ResponseBodyOfTheGetAccountSubmissionSnippetListMethod
     */
    result?: RpcGetAccountSubmissionSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetAccountSubmissionSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetAccountSubmissionSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetAccountSubmissionSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetAccountSubmissionSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetAccountSubmissionSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetAccountSubmissionSnippetListMethod(value: object): value is ResponseBodyOfTheGetAccountSubmissionSnippetListMethod {
    return true;
}

export function ResponseBodyOfTheGetAccountSubmissionSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetAccountSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetAccountSubmissionSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountSubmissionSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetAccountSubmissionSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetAccountSubmissionSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetAccountSubmissionSnippetListMethodToJSON(json: any): ResponseBodyOfTheGetAccountSubmissionSnippetListMethod {
    return ResponseBodyOfTheGetAccountSubmissionSnippetListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetAccountSubmissionSnippetListMethodToJSONTyped(value?: ResponseBodyOfTheGetAccountSubmissionSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetAccountSubmissionSnippetListResponseToJSON(value['result']),
    };
}

