/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateAccountResponse } from './RpcCreateAccountResponse';
import {
    RpcCreateAccountResponseFromJSON,
    RpcCreateAccountResponseFromJSONTyped,
    RpcCreateAccountResponseToJSON,
    RpcCreateAccountResponseToJSONTyped,
} from './RpcCreateAccountResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheCreateAccountMethod
 */
export interface ResponseBodyOfTheCreateAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheCreateAccountMethod
     */
    jsonrpc?: ResponseBodyOfTheCreateAccountMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheCreateAccountMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheCreateAccountMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcCreateAccountResponse}
     * @memberof ResponseBodyOfTheCreateAccountMethod
     */
    result?: RpcCreateAccountResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheCreateAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheCreateAccountMethodJsonrpcEnum = typeof ResponseBodyOfTheCreateAccountMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheCreateAccountMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheCreateAccountMethod interface.
 */
export function instanceOfResponseBodyOfTheCreateAccountMethod(value: object): value is ResponseBodyOfTheCreateAccountMethod {
    return true;
}

export function ResponseBodyOfTheCreateAccountMethodFromJSON(json: any): ResponseBodyOfTheCreateAccountMethod {
    return ResponseBodyOfTheCreateAccountMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheCreateAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcCreateAccountResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheCreateAccountMethodToJSON(json: any): ResponseBodyOfTheCreateAccountMethod {
    return ResponseBodyOfTheCreateAccountMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateAccountMethodToJSONTyped(value?: ResponseBodyOfTheCreateAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcCreateAccountResponseToJSON(value['result']),
    };
}

