/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUpdateAccountResponse } from './RpcUpdateAccountResponse';
import {
    RpcUpdateAccountResponseFromJSON,
    RpcUpdateAccountResponseFromJSONTyped,
    RpcUpdateAccountResponseToJSON,
    RpcUpdateAccountResponseToJSONTyped,
} from './RpcUpdateAccountResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheUpdateAccountMethod
 */
export interface ResponseBodyOfTheUpdateAccountMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    jsonrpc?: ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcUpdateAccountResponse}
     * @memberof ResponseBodyOfTheUpdateAccountMethod
     */
    result?: RpcUpdateAccountResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum = typeof ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheUpdateAccountMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheUpdateAccountMethod interface.
 */
export function instanceOfResponseBodyOfTheUpdateAccountMethod(value: object): value is ResponseBodyOfTheUpdateAccountMethod {
    return true;
}

export function ResponseBodyOfTheUpdateAccountMethodFromJSON(json: any): ResponseBodyOfTheUpdateAccountMethod {
    return ResponseBodyOfTheUpdateAccountMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateAccountMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheUpdateAccountMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcUpdateAccountResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheUpdateAccountMethodToJSON(json: any): ResponseBodyOfTheUpdateAccountMethod {
    return ResponseBodyOfTheUpdateAccountMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheUpdateAccountMethodToJSONTyped(value?: ResponseBodyOfTheUpdateAccountMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcUpdateAccountResponseToJSON(value['result']),
    };
}

