/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheDeleteSubmissionMethod
 */
export interface ResponseBodyOfTheDeleteSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    jsonrpc?: ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {object}
     * @memberof ResponseBodyOfTheDeleteSubmissionMethod
     */
    result?: object;
}


/**
 * @export
 */
export const ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum = typeof ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheDeleteSubmissionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheDeleteSubmissionMethod interface.
 */
export function instanceOfResponseBodyOfTheDeleteSubmissionMethod(value: object): value is ResponseBodyOfTheDeleteSubmissionMethod {
    return true;
}

export function ResponseBodyOfTheDeleteSubmissionMethodFromJSON(json: any): ResponseBodyOfTheDeleteSubmissionMethod {
    return ResponseBodyOfTheDeleteSubmissionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheDeleteSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : json['result'],
    };
}

export function ResponseBodyOfTheDeleteSubmissionMethodToJSON(json: any): ResponseBodyOfTheDeleteSubmissionMethod {
    return ResponseBodyOfTheDeleteSubmissionMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheDeleteSubmissionMethodToJSONTyped(value?: ResponseBodyOfTheDeleteSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': value['result'],
    };
}

