/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetSubmissionResponse } from './RpcGetSubmissionResponse';
import {
    RpcGetSubmissionResponseFromJSON,
    RpcGetSubmissionResponseFromJSONTyped,
    RpcGetSubmissionResponseToJSON,
    RpcGetSubmissionResponseToJSONTyped,
} from './RpcGetSubmissionResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetSubmissionMethod
 */
export interface ResponseBodyOfTheGetSubmissionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetSubmissionMethod
     */
    jsonrpc?: ResponseBodyOfTheGetSubmissionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetSubmissionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetSubmissionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetSubmissionResponse}
     * @memberof ResponseBodyOfTheGetSubmissionMethod
     */
    result?: RpcGetSubmissionResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetSubmissionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetSubmissionMethodJsonrpcEnum = typeof ResponseBodyOfTheGetSubmissionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetSubmissionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetSubmissionMethod interface.
 */
export function instanceOfResponseBodyOfTheGetSubmissionMethod(value: object): value is ResponseBodyOfTheGetSubmissionMethod {
    return true;
}

export function ResponseBodyOfTheGetSubmissionMethodFromJSON(json: any): ResponseBodyOfTheGetSubmissionMethod {
    return ResponseBodyOfTheGetSubmissionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetSubmissionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetSubmissionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetSubmissionResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetSubmissionMethodToJSON(json: any): ResponseBodyOfTheGetSubmissionMethod {
    return ResponseBodyOfTheGetSubmissionMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetSubmissionMethodToJSONTyped(value?: ResponseBodyOfTheGetSubmissionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetSubmissionResponseToJSON(value['result']),
    };
}

