/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetProblemSnippetListResponse } from './RpcGetProblemSnippetListResponse';
import {
    RpcGetProblemSnippetListResponseFromJSON,
    RpcGetProblemSnippetListResponseFromJSONTyped,
    RpcGetProblemSnippetListResponseToJSON,
    RpcGetProblemSnippetListResponseToJSONTyped,
} from './RpcGetProblemSnippetListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetProblemSnippetListMethod
 */
export interface ResponseBodyOfTheGetProblemSnippetListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemSnippetListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetProblemSnippetListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetProblemSnippetListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetProblemSnippetListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetProblemSnippetListResponse}
     * @memberof ResponseBodyOfTheGetProblemSnippetListMethod
     */
    result?: RpcGetProblemSnippetListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetProblemSnippetListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetProblemSnippetListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetProblemSnippetListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetProblemSnippetListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetProblemSnippetListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetProblemSnippetListMethod(value: object): value is ResponseBodyOfTheGetProblemSnippetListMethod {
    return true;
}

export function ResponseBodyOfTheGetProblemSnippetListMethodFromJSON(json: any): ResponseBodyOfTheGetProblemSnippetListMethod {
    return ResponseBodyOfTheGetProblemSnippetListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemSnippetListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetProblemSnippetListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetProblemSnippetListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetProblemSnippetListMethodToJSON(json: any): ResponseBodyOfTheGetProblemSnippetListMethod {
    return ResponseBodyOfTheGetProblemSnippetListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetProblemSnippetListMethodToJSONTyped(value?: ResponseBodyOfTheGetProblemSnippetListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetProblemSnippetListResponseToJSON(value['result']),
    };
}

