/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcCreateSessionResponse } from './RpcCreateSessionResponse';
import {
    RpcCreateSessionResponseFromJSON,
    RpcCreateSessionResponseFromJSONTyped,
    RpcCreateSessionResponseToJSON,
    RpcCreateSessionResponseToJSONTyped,
} from './RpcCreateSessionResponse';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheCreateSessionMethod
 */
export interface ResponseBodyOfTheCreateSessionMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheCreateSessionMethod
     */
    jsonrpc?: ResponseBodyOfTheCreateSessionMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheCreateSessionMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheCreateSessionMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcCreateSessionResponse}
     * @memberof ResponseBodyOfTheCreateSessionMethod
     */
    result?: RpcCreateSessionResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheCreateSessionMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheCreateSessionMethodJsonrpcEnum = typeof ResponseBodyOfTheCreateSessionMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheCreateSessionMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheCreateSessionMethod interface.
 */
export function instanceOfResponseBodyOfTheCreateSessionMethod(value: object): value is ResponseBodyOfTheCreateSessionMethod {
    return true;
}

export function ResponseBodyOfTheCreateSessionMethodFromJSON(json: any): ResponseBodyOfTheCreateSessionMethod {
    return ResponseBodyOfTheCreateSessionMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateSessionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheCreateSessionMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcCreateSessionResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheCreateSessionMethodToJSON(json: any): ResponseBodyOfTheCreateSessionMethod {
    return ResponseBodyOfTheCreateSessionMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheCreateSessionMethodToJSONTyped(value?: ResponseBodyOfTheCreateSessionMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcCreateSessionResponseToJSON(value['result']),
    };
}

