/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcError } from './RpcError';
import {
    RpcErrorFromJSON,
    RpcErrorFromJSONTyped,
    RpcErrorToJSON,
    RpcErrorToJSONTyped,
} from './RpcError';
import type { RpcGetUserListResponse } from './RpcGetUserListResponse';
import {
    RpcGetUserListResponseFromJSON,
    RpcGetUserListResponseFromJSONTyped,
    RpcGetUserListResponseToJSON,
    RpcGetUserListResponseToJSONTyped,
} from './RpcGetUserListResponse';

/**
 * 
 * @export
 * @interface ResponseBodyOfTheGetUserListMethod
 */
export interface ResponseBodyOfTheGetUserListMethod {
    /**
     * A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    jsonrpc?: ResponseBodyOfTheGetUserListMethodJsonrpcEnum;
    /**
     * It MUST be the same as the value of the id member in the Request.
     * @type {string}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    id?: string;
    /**
     * 
     * @type {RpcError}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    error?: RpcError;
    /**
     * 
     * @type {RpcGetUserListResponse}
     * @memberof ResponseBodyOfTheGetUserListMethod
     */
    result?: RpcGetUserListResponse;
}


/**
 * @export
 */
export const ResponseBodyOfTheGetUserListMethodJsonrpcEnum = {
    _20: '2.0'
} as const;
export type ResponseBodyOfTheGetUserListMethodJsonrpcEnum = typeof ResponseBodyOfTheGetUserListMethodJsonrpcEnum[keyof typeof ResponseBodyOfTheGetUserListMethodJsonrpcEnum];


/**
 * Check if a given object implements the ResponseBodyOfTheGetUserListMethod interface.
 */
export function instanceOfResponseBodyOfTheGetUserListMethod(value: object): value is ResponseBodyOfTheGetUserListMethod {
    return true;
}

export function ResponseBodyOfTheGetUserListMethodFromJSON(json: any): ResponseBodyOfTheGetUserListMethod {
    return ResponseBodyOfTheGetUserListMethodFromJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserListMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBodyOfTheGetUserListMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'id': json['id'] == null ? undefined : json['id'],
        'error': json['error'] == null ? undefined : RpcErrorFromJSON(json['error']),
        'result': json['result'] == null ? undefined : RpcGetUserListResponseFromJSON(json['result']),
    };
}

export function ResponseBodyOfTheGetUserListMethodToJSON(json: any): ResponseBodyOfTheGetUserListMethod {
    return ResponseBodyOfTheGetUserListMethodToJSONTyped(json, false);
}

export function ResponseBodyOfTheGetUserListMethodToJSONTyped(value?: ResponseBodyOfTheGetUserListMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'id': value['id'],
        'error': RpcErrorToJSON(value['error']),
        'result': RpcGetUserListResponseToJSON(value['result']),
    };
}

