/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - 
 * * `problem_setter` - 
 * * `contestant` - 
 * * `worker` - 
 * @export
 */
export const RpcAccountRole = {
    Admin: 'admin',
    ProblemSetter: 'problem_setter',
    Contestant: 'contestant',
    Worker: 'worker'
} as const;
export type RpcAccountRole = typeof RpcAccountRole[keyof typeof RpcAccountRole];


export function instanceOfRpcAccountRole(value: any): boolean {
    for (const key in RpcAccountRole) {
        if (Object.prototype.hasOwnProperty.call(RpcAccountRole, key)) {
            if (RpcAccountRole[key as keyof typeof RpcAccountRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RpcAccountRoleFromJSON(json: any): RpcAccountRole {
    return RpcAccountRoleFromJSONTyped(json, false);
}

export function RpcAccountRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcAccountRole {
    return json as RpcAccountRole;
}

export function RpcAccountRoleToJSON(value?: RpcAccountRole | null): any {
    return value as any;
}

export function RpcAccountRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): RpcAccountRole {
    return value as RpcAccountRole;
}

