/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccount } from './RpcAccount';
import {
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
    RpcAccountToJSONTyped,
} from './RpcAccount';

/**
 * 
 * @export
 * @interface RpcCreateAccountResponse
 */
export interface RpcCreateAccountResponse {
    /**
     * 
     * @type {RpcAccount}
     * @memberof RpcCreateAccountResponse
     */
    account: RpcAccount;
}

/**
 * Check if a given object implements the RpcCreateAccountResponse interface.
 */
export function instanceOfRpcCreateAccountResponse(value: object): value is RpcCreateAccountResponse {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function RpcCreateAccountResponseFromJSON(json: any): RpcCreateAccountResponse {
    return RpcCreateAccountResponseFromJSONTyped(json, false);
}

export function RpcCreateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': RpcAccountFromJSON(json['Account']),
    };
}

export function RpcCreateAccountResponseToJSON(json: any): RpcCreateAccountResponse {
    return RpcCreateAccountResponseToJSONTyped(json, false);
}

export function RpcCreateAccountResponseToJSONTyped(value?: RpcCreateAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Account': RpcAccountToJSON(value['account']),
    };
}

