/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcCreateTestCaseRequest
 */
export interface RpcCreateTestCaseRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcCreateTestCaseRequest
     */
    problemID: number;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateTestCaseRequest
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateTestCaseRequest
     */
    output: string;
    /**
     * 
     * @type {boolean}
     * @memberof RpcCreateTestCaseRequest
     */
    isHidden: boolean;
}

/**
 * Check if a given object implements the RpcCreateTestCaseRequest interface.
 */
export function instanceOfRpcCreateTestCaseRequest(value: object): value is RpcCreateTestCaseRequest {
    if (!('problemID' in value) || value['problemID'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    return true;
}

export function RpcCreateTestCaseRequestFromJSON(json: any): RpcCreateTestCaseRequest {
    return RpcCreateTestCaseRequestFromJSONTyped(json, false);
}

export function RpcCreateTestCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateTestCaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'problemID': json['ProblemID'],
        'input': json['Input'],
        'output': json['Output'],
        'isHidden': json['IsHidden'],
    };
}

export function RpcCreateTestCaseRequestToJSON(json: any): RpcCreateTestCaseRequest {
    return RpcCreateTestCaseRequestToJSONTyped(json, false);
}

export function RpcCreateTestCaseRequestToJSONTyped(value?: RpcCreateTestCaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProblemID': value['problemID'],
        'Input': value['input'],
        'Output': value['output'],
        'IsHidden': value['isHidden'],
    };
}

