/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccountRole } from './RpcAccountRole';
import {
    RpcAccountRoleFromJSON,
    RpcAccountRoleFromJSONTyped,
    RpcAccountRoleToJSON,
    RpcAccountRoleToJSONTyped,
} from './RpcAccountRole';

/**
 * 
 * @export
 * @interface RpcCreateAccountRequest
 */
export interface RpcCreateAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    accountName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    displayName: string;
    /**
     * 
     * @type {RpcAccountRole}
     * @memberof RpcCreateAccountRequest
     */
    role: RpcAccountRole;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateAccountRequest
     */
    password: string;
}



/**
 * Check if a given object implements the RpcCreateAccountRequest interface.
 */
export function instanceOfRpcCreateAccountRequest(value: object): value is RpcCreateAccountRequest {
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RpcCreateAccountRequestFromJSON(json: any): RpcCreateAccountRequest {
    return RpcCreateAccountRequestFromJSONTyped(json, false);
}

export function RpcCreateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountName': json['AccountName'],
        'displayName': json['DisplayName'],
        'role': RpcAccountRoleFromJSON(json['Role']),
        'password': json['Password'],
    };
}

export function RpcCreateAccountRequestToJSON(json: any): RpcCreateAccountRequest {
    return RpcCreateAccountRequestToJSONTyped(json, false);
}

export function RpcCreateAccountRequestToJSONTyped(value?: RpcCreateAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AccountName': value['accountName'],
        'DisplayName': value['displayName'],
        'Role': RpcAccountRoleToJSON(value['role']),
        'Password': value['password'],
    };
}

