/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcProblem } from './RpcProblem';
import {
    RpcProblemFromJSON,
    RpcProblemFromJSONTyped,
    RpcProblemToJSON,
    RpcProblemToJSONTyped,
} from './RpcProblem';

/**
 * 
 * @export
 * @interface RpcCreateSubmissionResponse
 */
export interface RpcCreateSubmissionResponse {
    /**
     * 
     * @type {RpcProblem}
     * @memberof RpcCreateSubmissionResponse
     */
    problem: RpcProblem;
}

/**
 * Check if a given object implements the RpcCreateSubmissionResponse interface.
 */
export function instanceOfRpcCreateSubmissionResponse(value: object): value is RpcCreateSubmissionResponse {
    if (!('problem' in value) || value['problem'] === undefined) return false;
    return true;
}

export function RpcCreateSubmissionResponseFromJSON(json: any): RpcCreateSubmissionResponse {
    return RpcCreateSubmissionResponseFromJSONTyped(json, false);
}

export function RpcCreateSubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateSubmissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'problem': RpcProblemFromJSON(json['Problem']),
    };
}

export function RpcCreateSubmissionResponseToJSON(json: any): RpcCreateSubmissionResponse {
    return RpcCreateSubmissionResponseToJSONTyped(json, false);
}

export function RpcCreateSubmissionResponseToJSONTyped(value?: RpcCreateSubmissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Problem': RpcProblemToJSON(value['problem']),
    };
}

