/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUser } from './RpcUser';
import {
    RpcUserFromJSON,
    RpcUserFromJSONTyped,
    RpcUserToJSON,
    RpcUserToJSONTyped,
} from './RpcUser';

/**
 * 
 * @export
 * @interface RpcCreateSessionResponse
 */
export interface RpcCreateSessionResponse {
    /**
     * 
     * @type {RpcUser}
     * @memberof RpcCreateSessionResponse
     */
    user: RpcUser;
}

/**
 * Check if a given object implements the RpcCreateSessionResponse interface.
 */
export function instanceOfRpcCreateSessionResponse(value: object): value is RpcCreateSessionResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function RpcCreateSessionResponseFromJSON(json: any): RpcCreateSessionResponse {
    return RpcCreateSessionResponseFromJSONTyped(json, false);
}

export function RpcCreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': RpcUserFromJSON(json['User']),
    };
}

export function RpcCreateSessionResponseToJSON(json: any): RpcCreateSessionResponse {
    return RpcCreateSessionResponseToJSONTyped(json, false);
}

export function RpcCreateSessionResponseToJSONTyped(value?: RpcCreateSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'User': RpcUserToJSON(value['user']),
    };
}

