/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUser } from './RpcUser';
import {
    RpcUserFromJSON,
    RpcUserFromJSONTyped,
    RpcUserToJSON,
    RpcUserToJSONTyped,
} from './RpcUser';

/**
 * 
 * @export
 * @interface RpcCreateUserResponse
 */
export interface RpcCreateUserResponse {
    /**
     * 
     * @type {RpcUser}
     * @memberof RpcCreateUserResponse
     */
    user: RpcUser;
}

/**
 * Check if a given object implements the RpcCreateUserResponse interface.
 */
export function instanceOfRpcCreateUserResponse(value: object): value is RpcCreateUserResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function RpcCreateUserResponseFromJSON(json: any): RpcCreateUserResponse {
    return RpcCreateUserResponseFromJSONTyped(json, false);
}

export function RpcCreateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': RpcUserFromJSON(json['User']),
    };
}

export function RpcCreateUserResponseToJSON(json: any): RpcCreateUserResponse {
    return RpcCreateUserResponseToJSONTyped(json, false);
}

export function RpcCreateUserResponseToJSONTyped(value?: RpcCreateUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'User': RpcUserToJSON(value['user']),
    };
}

