/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcCreateTestCaseListRequest
 */
export interface RpcCreateTestCaseListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcCreateTestCaseListRequest
     */
    problemID: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof RpcCreateTestCaseListRequest
     */
    zippedTestData: Array<number>;
}

/**
 * Check if a given object implements the RpcCreateTestCaseListRequest interface.
 */
export function instanceOfRpcCreateTestCaseListRequest(value: object): value is RpcCreateTestCaseListRequest {
    if (!('problemID' in value) || value['problemID'] === undefined) return false;
    if (!('zippedTestData' in value) || value['zippedTestData'] === undefined) return false;
    return true;
}

export function RpcCreateTestCaseListRequestFromJSON(json: any): RpcCreateTestCaseListRequest {
    return RpcCreateTestCaseListRequestFromJSONTyped(json, false);
}

export function RpcCreateTestCaseListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateTestCaseListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'problemID': json['ProblemID'],
        'zippedTestData': json['ZippedTestData'],
    };
}

export function RpcCreateTestCaseListRequestToJSON(json: any): RpcCreateTestCaseListRequest {
    return RpcCreateTestCaseListRequestToJSONTyped(json, false);
}

export function RpcCreateTestCaseListRequestToJSONTyped(value?: RpcCreateTestCaseListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProblemID': value['problemID'],
        'ZippedTestData': value['zippedTestData'],
    };
}

