/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcProblemExample } from './RpcProblemExample';
import {
    RpcProblemExampleFromJSON,
    RpcProblemExampleFromJSONTyped,
    RpcProblemExampleToJSON,
    RpcProblemExampleToJSONTyped,
} from './RpcProblemExample';

/**
 * 
 * @export
 * @interface RpcCreateProblemRequest
 */
export interface RpcCreateProblemRequest {
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RpcCreateProblemRequest
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemRequest
     */
    timeLimitInMillisecond: number;
    /**
     * 
     * @type {number}
     * @memberof RpcCreateProblemRequest
     */
    memoryLimitInByte: number;
    /**
     * 
     * @type {Array<RpcProblemExample>}
     * @memberof RpcCreateProblemRequest
     */
    exampleList: Array<RpcProblemExample>;
}

/**
 * Check if a given object implements the RpcCreateProblemRequest interface.
 */
export function instanceOfRpcCreateProblemRequest(value: object): value is RpcCreateProblemRequest {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('timeLimitInMillisecond' in value) || value['timeLimitInMillisecond'] === undefined) return false;
    if (!('memoryLimitInByte' in value) || value['memoryLimitInByte'] === undefined) return false;
    if (!('exampleList' in value) || value['exampleList'] === undefined) return false;
    return true;
}

export function RpcCreateProblemRequestFromJSON(json: any): RpcCreateProblemRequest {
    return RpcCreateProblemRequestFromJSONTyped(json, false);
}

export function RpcCreateProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcCreateProblemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['DisplayName'],
        'description': json['Description'],
        'timeLimitInMillisecond': json['TimeLimitInMillisecond'],
        'memoryLimitInByte': json['MemoryLimitInByte'],
        'exampleList': ((json['ExampleList'] as Array<any>).map(RpcProblemExampleFromJSON)),
    };
}

export function RpcCreateProblemRequestToJSON(json: any): RpcCreateProblemRequest {
    return RpcCreateProblemRequestToJSONTyped(json, false);
}

export function RpcCreateProblemRequestToJSONTyped(value?: RpcCreateProblemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'DisplayName': value['displayName'],
        'Description': value['description'],
        'TimeLimitInMillisecond': value['timeLimitInMillisecond'],
        'MemoryLimitInByte': value['memoryLimitInByte'],
        'ExampleList': ((value['exampleList'] as Array<any>).map(RpcProblemExampleToJSON)),
    };
}

