/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcDeleteTestCaseRequest
 */
export interface RpcDeleteTestCaseRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcDeleteTestCaseRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcDeleteTestCaseRequest interface.
 */
export function instanceOfRpcDeleteTestCaseRequest(value: object): value is RpcDeleteTestCaseRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcDeleteTestCaseRequestFromJSON(json: any): RpcDeleteTestCaseRequest {
    return RpcDeleteTestCaseRequestFromJSONTyped(json, false);
}

export function RpcDeleteTestCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcDeleteTestCaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcDeleteTestCaseRequestToJSON(json: any): RpcDeleteTestCaseRequest {
    return RpcDeleteTestCaseRequestToJSONTyped(json, false);
}

export function RpcDeleteTestCaseRequestToJSONTyped(value?: RpcDeleteTestCaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

