/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcDeleteProblemRequest
 */
export interface RpcDeleteProblemRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcDeleteProblemRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcDeleteProblemRequest interface.
 */
export function instanceOfRpcDeleteProblemRequest(value: object): value is RpcDeleteProblemRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcDeleteProblemRequestFromJSON(json: any): RpcDeleteProblemRequest {
    return RpcDeleteProblemRequestFromJSONTyped(json, false);
}

export function RpcDeleteProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcDeleteProblemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcDeleteProblemRequestToJSON(json: any): RpcDeleteProblemRequest {
    return RpcDeleteProblemRequestToJSONTyped(json, false);
}

export function RpcDeleteProblemRequestToJSONTyped(value?: RpcDeleteProblemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

