/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcDeleteSubmissionRequest
 */
export interface RpcDeleteSubmissionRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcDeleteSubmissionRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcDeleteSubmissionRequest interface.
 */
export function instanceOfRpcDeleteSubmissionRequest(value: object): value is RpcDeleteSubmissionRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcDeleteSubmissionRequestFromJSON(json: any): RpcDeleteSubmissionRequest {
    return RpcDeleteSubmissionRequestFromJSONTyped(json, false);
}

export function RpcDeleteSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcDeleteSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcDeleteSubmissionRequestToJSON(json: any): RpcDeleteSubmissionRequest {
    return RpcDeleteSubmissionRequestToJSONTyped(json, false);
}

export function RpcDeleteSubmissionRequestToJSONTyped(value?: RpcDeleteSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

