/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetUserListRequest
 */
export interface RpcGetUserListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetUserListRequest interface.
 */
export function instanceOfRpcGetUserListRequest(value: object): value is RpcGetUserListRequest {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetUserListRequestFromJSON(json: any): RpcGetUserListRequest {
    return RpcGetUserListRequestFromJSONTyped(json, false);
}

export function RpcGetUserListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetUserListRequestToJSON(json: any): RpcGetUserListRequest {
    return RpcGetUserListRequestToJSONTyped(json, false);
}

export function RpcGetUserListRequestToJSONTyped(value?: RpcGetUserListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

