/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetSubmissionRequest
 */
export interface RpcGetSubmissionRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetSubmissionRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcGetSubmissionRequest interface.
 */
export function instanceOfRpcGetSubmissionRequest(value: object): value is RpcGetSubmissionRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcGetSubmissionRequestFromJSON(json: any): RpcGetSubmissionRequest {
    return RpcGetSubmissionRequestFromJSONTyped(json, false);
}

export function RpcGetSubmissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetSubmissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcGetSubmissionRequestToJSON(json: any): RpcGetSubmissionRequest {
    return RpcGetSubmissionRequestToJSONTyped(json, false);
}

export function RpcGetSubmissionRequestToJSONTyped(value?: RpcGetSubmissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

