/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetProblemSubmissionSnippetListRequest
 */
export interface RpcGetProblemSubmissionSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemSubmissionSnippetListRequest
     */
    problemID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemSubmissionSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemSubmissionSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetProblemSubmissionSnippetListRequest interface.
 */
export function instanceOfRpcGetProblemSubmissionSnippetListRequest(value: object): value is RpcGetProblemSubmissionSnippetListRequest {
    if (!('problemID' in value) || value['problemID'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetProblemSubmissionSnippetListRequestFromJSON(json: any): RpcGetProblemSubmissionSnippetListRequest {
    return RpcGetProblemSubmissionSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetProblemSubmissionSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemSubmissionSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'problemID': json['ProblemID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetProblemSubmissionSnippetListRequestToJSON(json: any): RpcGetProblemSubmissionSnippetListRequest {
    return RpcGetProblemSubmissionSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetProblemSubmissionSnippetListRequestToJSONTyped(value?: RpcGetProblemSubmissionSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProblemID': value['problemID'],
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

