/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetUserRequest
 */
export interface RpcGetUserRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcGetUserRequest interface.
 */
export function instanceOfRpcGetUserRequest(value: object): value is RpcGetUserRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcGetUserRequestFromJSON(json: any): RpcGetUserRequest {
    return RpcGetUserRequestFromJSONTyped(json, false);
}

export function RpcGetUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcGetUserRequestToJSON(json: any): RpcGetUserRequest {
    return RpcGetUserRequestToJSONTyped(json, false);
}

export function RpcGetUserRequestToJSONTyped(value?: RpcGetUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

