/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetUserProblemSnippetListRequest
 */
export interface RpcGetUserProblemSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserProblemSnippetListRequest
     */
    userID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserProblemSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetUserProblemSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetUserProblemSnippetListRequest interface.
 */
export function instanceOfRpcGetUserProblemSnippetListRequest(value: object): value is RpcGetUserProblemSnippetListRequest {
    if (!('userID' in value) || value['userID'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetUserProblemSnippetListRequestFromJSON(json: any): RpcGetUserProblemSnippetListRequest {
    return RpcGetUserProblemSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetUserProblemSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserProblemSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userID': json['UserID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetUserProblemSnippetListRequestToJSON(json: any): RpcGetUserProblemSnippetListRequest {
    return RpcGetUserProblemSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetUserProblemSnippetListRequestToJSONTyped(value?: RpcGetUserProblemSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'UserID': value['userID'],
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

