/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUser } from './RpcUser';
import {
    RpcUserFromJSON,
    RpcUserFromJSONTyped,
    RpcUserToJSON,
    RpcUserToJSONTyped,
} from './RpcUser';

/**
 * 
 * @export
 * @interface RpcGetUserResponse
 */
export interface RpcGetUserResponse {
    /**
     * 
     * @type {RpcUser}
     * @memberof RpcGetUserResponse
     */
    user: RpcUser;
}

/**
 * Check if a given object implements the RpcGetUserResponse interface.
 */
export function instanceOfRpcGetUserResponse(value: object): value is RpcGetUserResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function RpcGetUserResponseFromJSON(json: any): RpcGetUserResponse {
    return RpcGetUserResponseFromJSONTyped(json, false);
}

export function RpcGetUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': RpcUserFromJSON(json['User']),
    };
}

export function RpcGetUserResponseToJSON(json: any): RpcGetUserResponse {
    return RpcGetUserResponseToJSONTyped(json, false);
}

export function RpcGetUserResponseToJSONTyped(value?: RpcGetUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'User': RpcUserToJSON(value['user']),
    };
}

