/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetTestCaseRequest
 */
export interface RpcGetTestCaseRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetTestCaseRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcGetTestCaseRequest interface.
 */
export function instanceOfRpcGetTestCaseRequest(value: object): value is RpcGetTestCaseRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcGetTestCaseRequestFromJSON(json: any): RpcGetTestCaseRequest {
    return RpcGetTestCaseRequestFromJSONTyped(json, false);
}

export function RpcGetTestCaseRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetTestCaseRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcGetTestCaseRequestToJSON(json: any): RpcGetTestCaseRequest {
    return RpcGetTestCaseRequestToJSONTyped(json, false);
}

export function RpcGetTestCaseRequestToJSONTyped(value?: RpcGetTestCaseRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

