/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccount } from './RpcAccount';
import {
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
    RpcAccountToJSONTyped,
} from './RpcAccount';

/**
 * 
 * @export
 * @interface RpcGetAccountListResponse
 */
export interface RpcGetAccountListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountListResponse
     */
    totalAccountCount: number;
    /**
     * 
     * @type {Array<RpcAccount>}
     * @memberof RpcGetAccountListResponse
     */
    accountList: Array<RpcAccount>;
}

/**
 * Check if a given object implements the RpcGetAccountListResponse interface.
 */
export function instanceOfRpcGetAccountListResponse(value: object): value is RpcGetAccountListResponse {
    if (!('totalAccountCount' in value) || value['totalAccountCount'] === undefined) return false;
    if (!('accountList' in value) || value['accountList'] === undefined) return false;
    return true;
}

export function RpcGetAccountListResponseFromJSON(json: any): RpcGetAccountListResponse {
    return RpcGetAccountListResponseFromJSONTyped(json, false);
}

export function RpcGetAccountListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalAccountCount': json['TotalAccountCount'],
        'accountList': ((json['AccountList'] as Array<any>).map(RpcAccountFromJSON)),
    };
}

export function RpcGetAccountListResponseToJSON(json: any): RpcGetAccountListResponse {
    return RpcGetAccountListResponseToJSONTyped(json, false);
}

export function RpcGetAccountListResponseToJSONTyped(value?: RpcGetAccountListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TotalAccountCount': value['totalAccountCount'],
        'AccountList': ((value['accountList'] as Array<any>).map(RpcAccountToJSON)),
    };
}

