/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcProblem } from './RpcProblem';
import {
    RpcProblemFromJSON,
    RpcProblemFromJSONTyped,
    RpcProblemToJSON,
    RpcProblemToJSONTyped,
} from './RpcProblem';

/**
 * 
 * @export
 * @interface RpcGetProblemSnippetListResponse
 */
export interface RpcGetProblemSnippetListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemSnippetListResponse
     */
    totalProblemCount: number;
    /**
     * 
     * @type {Array<RpcProblem>}
     * @memberof RpcGetProblemSnippetListResponse
     */
    problemSnippetList: Array<RpcProblem>;
}

/**
 * Check if a given object implements the RpcGetProblemSnippetListResponse interface.
 */
export function instanceOfRpcGetProblemSnippetListResponse(value: object): value is RpcGetProblemSnippetListResponse {
    if (!('totalProblemCount' in value) || value['totalProblemCount'] === undefined) return false;
    if (!('problemSnippetList' in value) || value['problemSnippetList'] === undefined) return false;
    return true;
}

export function RpcGetProblemSnippetListResponseFromJSON(json: any): RpcGetProblemSnippetListResponse {
    return RpcGetProblemSnippetListResponseFromJSONTyped(json, false);
}

export function RpcGetProblemSnippetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemSnippetListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalProblemCount': json['TotalProblemCount'],
        'problemSnippetList': ((json['ProblemSnippetList'] as Array<any>).map(RpcProblemFromJSON)),
    };
}

export function RpcGetProblemSnippetListResponseToJSON(json: any): RpcGetProblemSnippetListResponse {
    return RpcGetProblemSnippetListResponseToJSONTyped(json, false);
}

export function RpcGetProblemSnippetListResponseToJSONTyped(value?: RpcGetProblemSnippetListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TotalProblemCount': value['totalProblemCount'],
        'ProblemSnippetList': ((value['problemSnippetList'] as Array<any>).map(RpcProblemToJSON)),
    };
}

