/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetAccountListRequest
 */
export interface RpcGetAccountListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetAccountListRequest interface.
 */
export function instanceOfRpcGetAccountListRequest(value: object): value is RpcGetAccountListRequest {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetAccountListRequestFromJSON(json: any): RpcGetAccountListRequest {
    return RpcGetAccountListRequestFromJSONTyped(json, false);
}

export function RpcGetAccountListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetAccountListRequestToJSON(json: any): RpcGetAccountListRequest {
    return RpcGetAccountListRequestToJSONTyped(json, false);
}

export function RpcGetAccountListRequestToJSONTyped(value?: RpcGetAccountListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

