/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcTestCase } from './RpcTestCase';
import {
    RpcTestCaseFromJSON,
    RpcTestCaseFromJSONTyped,
    RpcTestCaseToJSON,
    RpcTestCaseToJSONTyped,
} from './RpcTestCase';

/**
 * 
 * @export
 * @interface RpcGetTestCaseResponse
 */
export interface RpcGetTestCaseResponse {
    /**
     * 
     * @type {RpcTestCase}
     * @memberof RpcGetTestCaseResponse
     */
    testCase: RpcTestCase;
}

/**
 * Check if a given object implements the RpcGetTestCaseResponse interface.
 */
export function instanceOfRpcGetTestCaseResponse(value: object): value is RpcGetTestCaseResponse {
    if (!('testCase' in value) || value['testCase'] === undefined) return false;
    return true;
}

export function RpcGetTestCaseResponseFromJSON(json: any): RpcGetTestCaseResponse {
    return RpcGetTestCaseResponseFromJSONTyped(json, false);
}

export function RpcGetTestCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetTestCaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'testCase': RpcTestCaseFromJSON(json['TestCase']),
    };
}

export function RpcGetTestCaseResponseToJSON(json: any): RpcGetTestCaseResponse {
    return RpcGetTestCaseResponseToJSONTyped(json, false);
}

export function RpcGetTestCaseResponseToJSONTyped(value?: RpcGetTestCaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TestCase': RpcTestCaseToJSON(value['testCase']),
    };
}

