/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcProblem } from './RpcProblem';
import {
    RpcProblemFromJSON,
    RpcProblemFromJSONTyped,
    RpcProblemToJSON,
    RpcProblemToJSONTyped,
} from './RpcProblem';

/**
 * 
 * @export
 * @interface RpcGetProblemResponse
 */
export interface RpcGetProblemResponse {
    /**
     * 
     * @type {RpcProblem}
     * @memberof RpcGetProblemResponse
     */
    problem: RpcProblem;
}

/**
 * Check if a given object implements the RpcGetProblemResponse interface.
 */
export function instanceOfRpcGetProblemResponse(value: object): value is RpcGetProblemResponse {
    if (!('problem' in value) || value['problem'] === undefined) return false;
    return true;
}

export function RpcGetProblemResponseFromJSON(json: any): RpcGetProblemResponse {
    return RpcGetProblemResponseFromJSONTyped(json, false);
}

export function RpcGetProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'problem': RpcProblemFromJSON(json['Problem']),
    };
}

export function RpcGetProblemResponseToJSON(json: any): RpcGetProblemResponse {
    return RpcGetProblemResponseToJSONTyped(json, false);
}

export function RpcGetProblemResponseToJSONTyped(value?: RpcGetProblemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Problem': RpcProblemToJSON(value['problem']),
    };
}

