/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccount } from './RpcAccount';
import {
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
    RpcAccountToJSONTyped,
} from './RpcAccount';

/**
 * 
 * @export
 * @interface RpcGetAccountResponse
 */
export interface RpcGetAccountResponse {
    /**
     * 
     * @type {RpcAccount}
     * @memberof RpcGetAccountResponse
     */
    account: RpcAccount;
}

/**
 * Check if a given object implements the RpcGetAccountResponse interface.
 */
export function instanceOfRpcGetAccountResponse(value: object): value is RpcGetAccountResponse {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function RpcGetAccountResponseFromJSON(json: any): RpcGetAccountResponse {
    return RpcGetAccountResponseFromJSONTyped(json, false);
}

export function RpcGetAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': RpcAccountFromJSON(json['Account']),
    };
}

export function RpcGetAccountResponseToJSON(json: any): RpcGetAccountResponse {
    return RpcGetAccountResponseToJSONTyped(json, false);
}

export function RpcGetAccountResponseToJSONTyped(value?: RpcGetAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Account': RpcAccountToJSON(value['account']),
    };
}

