/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetAccountRequest
 */
export interface RpcGetAccountRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcGetAccountRequest interface.
 */
export function instanceOfRpcGetAccountRequest(value: object): value is RpcGetAccountRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcGetAccountRequestFromJSON(json: any): RpcGetAccountRequest {
    return RpcGetAccountRequestFromJSONTyped(json, false);
}

export function RpcGetAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcGetAccountRequestToJSON(json: any): RpcGetAccountRequest {
    return RpcGetAccountRequestToJSONTyped(json, false);
}

export function RpcGetAccountRequestToJSONTyped(value?: RpcGetAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

