/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetAccountProblemSnippetListRequest
 */
export interface RpcGetAccountProblemSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountProblemSnippetListRequest
     */
    accountID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountProblemSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountProblemSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetAccountProblemSnippetListRequest interface.
 */
export function instanceOfRpcGetAccountProblemSnippetListRequest(value: object): value is RpcGetAccountProblemSnippetListRequest {
    if (!('accountID' in value) || value['accountID'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetAccountProblemSnippetListRequestFromJSON(json: any): RpcGetAccountProblemSnippetListRequest {
    return RpcGetAccountProblemSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetAccountProblemSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountProblemSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountID': json['AccountID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetAccountProblemSnippetListRequestToJSON(json: any): RpcGetAccountProblemSnippetListRequest {
    return RpcGetAccountProblemSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetAccountProblemSnippetListRequestToJSONTyped(value?: RpcGetAccountProblemSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AccountID': value['accountID'],
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

