/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetSubmissionSnippetListRequest
 */
export interface RpcGetSubmissionSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetSubmissionSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetSubmissionSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetSubmissionSnippetListRequest interface.
 */
export function instanceOfRpcGetSubmissionSnippetListRequest(value: object): value is RpcGetSubmissionSnippetListRequest {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetSubmissionSnippetListRequestFromJSON(json: any): RpcGetSubmissionSnippetListRequest {
    return RpcGetSubmissionSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetSubmissionSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetSubmissionSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetSubmissionSnippetListRequestToJSON(json: any): RpcGetSubmissionSnippetListRequest {
    return RpcGetSubmissionSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetSubmissionSnippetListRequestToJSONTyped(value?: RpcGetSubmissionSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

