/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetProblemRequest
 */
export interface RpcGetProblemRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemRequest
     */
    iD: number;
}

/**
 * Check if a given object implements the RpcGetProblemRequest interface.
 */
export function instanceOfRpcGetProblemRequest(value: object): value is RpcGetProblemRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    return true;
}

export function RpcGetProblemRequestFromJSON(json: any): RpcGetProblemRequest {
    return RpcGetProblemRequestFromJSONTyped(json, false);
}

export function RpcGetProblemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
    };
}

export function RpcGetProblemRequestToJSON(json: any): RpcGetProblemRequest {
    return RpcGetProblemRequestToJSONTyped(json, false);
}

export function RpcGetProblemRequestToJSONTyped(value?: RpcGetProblemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
    };
}

