/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcTestCaseSnippet } from './RpcTestCaseSnippet';
import {
    RpcTestCaseSnippetFromJSON,
    RpcTestCaseSnippetFromJSONTyped,
    RpcTestCaseSnippetToJSON,
    RpcTestCaseSnippetToJSONTyped,
} from './RpcTestCaseSnippet';

/**
 * 
 * @export
 * @interface RpcGetProblemTestCaseSnippetListResponse
 */
export interface RpcGetProblemTestCaseSnippetListResponse {
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemTestCaseSnippetListResponse
     */
    totalTestCaseCount: number;
    /**
     * 
     * @type {Array<RpcTestCaseSnippet>}
     * @memberof RpcGetProblemTestCaseSnippetListResponse
     */
    testCaseSnippetList: Array<RpcTestCaseSnippet>;
}

/**
 * Check if a given object implements the RpcGetProblemTestCaseSnippetListResponse interface.
 */
export function instanceOfRpcGetProblemTestCaseSnippetListResponse(value: object): value is RpcGetProblemTestCaseSnippetListResponse {
    if (!('totalTestCaseCount' in value) || value['totalTestCaseCount'] === undefined) return false;
    if (!('testCaseSnippetList' in value) || value['testCaseSnippetList'] === undefined) return false;
    return true;
}

export function RpcGetProblemTestCaseSnippetListResponseFromJSON(json: any): RpcGetProblemTestCaseSnippetListResponse {
    return RpcGetProblemTestCaseSnippetListResponseFromJSONTyped(json, false);
}

export function RpcGetProblemTestCaseSnippetListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemTestCaseSnippetListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalTestCaseCount': json['TotalTestCaseCount'],
        'testCaseSnippetList': ((json['TestCaseSnippetList'] as Array<any>).map(RpcTestCaseSnippetFromJSON)),
    };
}

export function RpcGetProblemTestCaseSnippetListResponseToJSON(json: any): RpcGetProblemTestCaseSnippetListResponse {
    return RpcGetProblemTestCaseSnippetListResponseToJSONTyped(json, false);
}

export function RpcGetProblemTestCaseSnippetListResponseToJSONTyped(value?: RpcGetProblemTestCaseSnippetListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TotalTestCaseCount': value['totalTestCaseCount'],
        'TestCaseSnippetList': ((value['testCaseSnippetList'] as Array<any>).map(RpcTestCaseSnippetToJSON)),
    };
}

