/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetProblemTestCaseSnippetListRequest
 */
export interface RpcGetProblemTestCaseSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemTestCaseSnippetListRequest
     */
    problemID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemTestCaseSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetProblemTestCaseSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetProblemTestCaseSnippetListRequest interface.
 */
export function instanceOfRpcGetProblemTestCaseSnippetListRequest(value: object): value is RpcGetProblemTestCaseSnippetListRequest {
    if (!('problemID' in value) || value['problemID'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetProblemTestCaseSnippetListRequestFromJSON(json: any): RpcGetProblemTestCaseSnippetListRequest {
    return RpcGetProblemTestCaseSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetProblemTestCaseSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetProblemTestCaseSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'problemID': json['ProblemID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetProblemTestCaseSnippetListRequestToJSON(json: any): RpcGetProblemTestCaseSnippetListRequest {
    return RpcGetProblemTestCaseSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetProblemTestCaseSnippetListRequestToJSONTyped(value?: RpcGetProblemTestCaseSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ProblemID': value['problemID'],
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

