/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcGetAccountSubmissionSnippetListRequest
 */
export interface RpcGetAccountSubmissionSnippetListRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountSubmissionSnippetListRequest
     */
    accountID: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountSubmissionSnippetListRequest
     */
    offset: number;
    /**
     * 
     * @type {number}
     * @memberof RpcGetAccountSubmissionSnippetListRequest
     */
    limit: number;
}

/**
 * Check if a given object implements the RpcGetAccountSubmissionSnippetListRequest interface.
 */
export function instanceOfRpcGetAccountSubmissionSnippetListRequest(value: object): value is RpcGetAccountSubmissionSnippetListRequest {
    if (!('accountID' in value) || value['accountID'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function RpcGetAccountSubmissionSnippetListRequestFromJSON(json: any): RpcGetAccountSubmissionSnippetListRequest {
    return RpcGetAccountSubmissionSnippetListRequestFromJSONTyped(json, false);
}

export function RpcGetAccountSubmissionSnippetListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetAccountSubmissionSnippetListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountID': json['AccountID'],
        'offset': json['Offset'],
        'limit': json['Limit'],
    };
}

export function RpcGetAccountSubmissionSnippetListRequestToJSON(json: any): RpcGetAccountSubmissionSnippetListRequest {
    return RpcGetAccountSubmissionSnippetListRequestToJSONTyped(json, false);
}

export function RpcGetAccountSubmissionSnippetListRequestToJSONTyped(value?: RpcGetAccountSubmissionSnippetListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'AccountID': value['accountID'],
        'Offset': value['offset'],
        'Limit': value['limit'],
    };
}

