/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcSubmission } from './RpcSubmission';
import {
    RpcSubmissionFromJSON,
    RpcSubmissionFromJSONTyped,
    RpcSubmissionToJSON,
    RpcSubmissionToJSONTyped,
} from './RpcSubmission';

/**
 * 
 * @export
 * @interface RpcGetSubmissionResponse
 */
export interface RpcGetSubmissionResponse {
    /**
     * 
     * @type {RpcSubmission}
     * @memberof RpcGetSubmissionResponse
     */
    submission: RpcSubmission;
}

/**
 * Check if a given object implements the RpcGetSubmissionResponse interface.
 */
export function instanceOfRpcGetSubmissionResponse(value: object): value is RpcGetSubmissionResponse {
    if (!('submission' in value) || value['submission'] === undefined) return false;
    return true;
}

export function RpcGetSubmissionResponseFromJSON(json: any): RpcGetSubmissionResponse {
    return RpcGetSubmissionResponseFromJSONTyped(json, false);
}

export function RpcGetSubmissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcGetSubmissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'submission': RpcSubmissionFromJSON(json['Submission']),
    };
}

export function RpcGetSubmissionResponseToJSON(json: any): RpcGetSubmissionResponse {
    return RpcGetSubmissionResponseToJSONTyped(json, false);
}

export function RpcGetSubmissionResponseToJSONTyped(value?: RpcGetSubmissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Submission': RpcSubmissionToJSON(value['submission']),
    };
}

