/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcProblemExample
 */
export interface RpcProblemExample {
    /**
     * 
     * @type {number}
     * @memberof RpcProblemExample
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcProblemExample
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcProblemExample
     */
    output: string;
}

/**
 * Check if a given object implements the RpcProblemExample interface.
 */
export function instanceOfRpcProblemExample(value: object): value is RpcProblemExample {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    return true;
}

export function RpcProblemExampleFromJSON(json: any): RpcProblemExample {
    return RpcProblemExampleFromJSONTyped(json, false);
}

export function RpcProblemExampleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcProblemExample {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'input': json['Input'],
        'output': json['Output'],
    };
}

export function RpcProblemExampleToJSON(json: any): RpcProblemExample {
    return RpcProblemExampleToJSONTyped(json, false);
}

export function RpcProblemExampleToJSONTyped(value?: RpcProblemExample | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'Input': value['input'],
        'Output': value['output'],
    };
}

