/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcSubmissionProblemSnippet
 */
export interface RpcSubmissionProblemSnippet {
    /**
     * 
     * @type {number}
     * @memberof RpcSubmissionProblemSnippet
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcSubmissionProblemSnippet
     */
    displayName: string;
}

/**
 * Check if a given object implements the RpcSubmissionProblemSnippet interface.
 */
export function instanceOfRpcSubmissionProblemSnippet(value: object): value is RpcSubmissionProblemSnippet {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function RpcSubmissionProblemSnippetFromJSON(json: any): RpcSubmissionProblemSnippet {
    return RpcSubmissionProblemSnippetFromJSONTyped(json, false);
}

export function RpcSubmissionProblemSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionProblemSnippet {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'displayName': json['DisplayName'],
    };
}

export function RpcSubmissionProblemSnippetToJSON(json: any): RpcSubmissionProblemSnippet {
    return RpcSubmissionProblemSnippetToJSONTyped(json, false);
}

export function RpcSubmissionProblemSnippetToJSONTyped(value?: RpcSubmissionProblemSnippet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'DisplayName': value['displayName'],
    };
}

