/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `1` - 
 * * `2` - 
 * * `3` - 
 * * `4` - 
 * * `5` - 
 * * `6` - 
 * @export
 */
export const RpcSubmissionResult = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type RpcSubmissionResult = typeof RpcSubmissionResult[keyof typeof RpcSubmissionResult];


export function instanceOfRpcSubmissionResult(value: any): boolean {
    for (const key in RpcSubmissionResult) {
        if (Object.prototype.hasOwnProperty.call(RpcSubmissionResult, key)) {
            if (RpcSubmissionResult[key as keyof typeof RpcSubmissionResult] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RpcSubmissionResultFromJSON(json: any): RpcSubmissionResult {
    return RpcSubmissionResultFromJSONTyped(json, false);
}

export function RpcSubmissionResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionResult {
    return json as RpcSubmissionResult;
}

export function RpcSubmissionResultToJSON(value?: RpcSubmissionResult | null): any {
    return value as any;
}

export function RpcSubmissionResultToJSONTyped(value: any, ignoreDiscriminator: boolean): RpcSubmissionResult {
    return value as RpcSubmissionResult;
}

