/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `1` - 
 * * `2` - 
 * * `3` - 
 * @export
 */
export const RpcSubmissionStatus = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;
export type RpcSubmissionStatus = typeof RpcSubmissionStatus[keyof typeof RpcSubmissionStatus];


export function instanceOfRpcSubmissionStatus(value: any): boolean {
    for (const key in RpcSubmissionStatus) {
        if (Object.prototype.hasOwnProperty.call(RpcSubmissionStatus, key)) {
            if (RpcSubmissionStatus[key as keyof typeof RpcSubmissionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RpcSubmissionStatusFromJSON(json: any): RpcSubmissionStatus {
    return RpcSubmissionStatusFromJSONTyped(json, false);
}

export function RpcSubmissionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcSubmissionStatus {
    return json as RpcSubmissionStatus;
}

export function RpcSubmissionStatusToJSON(value?: RpcSubmissionStatus | null): any {
    return value as any;
}

export function RpcSubmissionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): RpcSubmissionStatus {
    return value as RpcSubmissionStatus;
}

