/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcTestCaseSnippet
 */
export interface RpcTestCaseSnippet {
    /**
     * 
     * @type {number}
     * @memberof RpcTestCaseSnippet
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcTestCaseSnippet
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcTestCaseSnippet
     */
    output: string;
    /**
     * 
     * @type {boolean}
     * @memberof RpcTestCaseSnippet
     */
    isHidden: boolean;
}

/**
 * Check if a given object implements the RpcTestCaseSnippet interface.
 */
export function instanceOfRpcTestCaseSnippet(value: object): value is RpcTestCaseSnippet {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    return true;
}

export function RpcTestCaseSnippetFromJSON(json: any): RpcTestCaseSnippet {
    return RpcTestCaseSnippetFromJSONTyped(json, false);
}

export function RpcTestCaseSnippetFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcTestCaseSnippet {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'input': json['Input'],
        'output': json['Output'],
        'isHidden': json['IsHidden'],
    };
}

export function RpcTestCaseSnippetToJSON(json: any): RpcTestCaseSnippet {
    return RpcTestCaseSnippetToJSONTyped(json, false);
}

export function RpcTestCaseSnippetToJSONTyped(value?: RpcTestCaseSnippet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'Input': value['input'],
        'Output': value['output'],
        'IsHidden': value['isHidden'],
    };
}

