/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RpcTestCase
 */
export interface RpcTestCase {
    /**
     * 
     * @type {number}
     * @memberof RpcTestCase
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcTestCase
     */
    input: string;
    /**
     * 
     * @type {string}
     * @memberof RpcTestCase
     */
    output: string;
    /**
     * 
     * @type {boolean}
     * @memberof RpcTestCase
     */
    isHidden: boolean;
}

/**
 * Check if a given object implements the RpcTestCase interface.
 */
export function instanceOfRpcTestCase(value: object): value is RpcTestCase {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    return true;
}

export function RpcTestCaseFromJSON(json: any): RpcTestCase {
    return RpcTestCaseFromJSONTyped(json, false);
}

export function RpcTestCaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcTestCase {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'input': json['Input'],
        'output': json['Output'],
        'isHidden': json['IsHidden'],
    };
}

export function RpcTestCaseToJSON(json: any): RpcTestCase {
    return RpcTestCaseToJSONTyped(json, false);
}

export function RpcTestCaseToJSONTyped(value?: RpcTestCase | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'Input': value['input'],
        'Output': value['output'],
        'IsHidden': value['isHidden'],
    };
}

