/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcUser } from './RpcUser';
import {
    RpcUserFromJSON,
    RpcUserFromJSONTyped,
    RpcUserToJSON,
    RpcUserToJSONTyped,
} from './RpcUser';

/**
 * 
 * @export
 * @interface RpcUpdateUserResponse
 */
export interface RpcUpdateUserResponse {
    /**
     * 
     * @type {RpcUser}
     * @memberof RpcUpdateUserResponse
     */
    user: RpcUser;
}

/**
 * Check if a given object implements the RpcUpdateUserResponse interface.
 */
export function instanceOfRpcUpdateUserResponse(value: object): value is RpcUpdateUserResponse {
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function RpcUpdateUserResponseFromJSON(json: any): RpcUpdateUserResponse {
    return RpcUpdateUserResponseFromJSONTyped(json, false);
}

export function RpcUpdateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'user': RpcUserFromJSON(json['User']),
    };
}

export function RpcUpdateUserResponseToJSON(json: any): RpcUpdateUserResponse {
    return RpcUpdateUserResponseToJSONTyped(json, false);
}

export function RpcUpdateUserResponseToJSONTyped(value?: RpcUpdateUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'User': RpcUserToJSON(value['user']),
    };
}

