/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcProblem } from './RpcProblem';
import {
    RpcProblemFromJSON,
    RpcProblemFromJSONTyped,
    RpcProblemToJSON,
    RpcProblemToJSONTyped,
} from './RpcProblem';

/**
 * 
 * @export
 * @interface RpcUpdateProblemResponse
 */
export interface RpcUpdateProblemResponse {
    /**
     * 
     * @type {RpcProblem}
     * @memberof RpcUpdateProblemResponse
     */
    problem: RpcProblem;
}

/**
 * Check if a given object implements the RpcUpdateProblemResponse interface.
 */
export function instanceOfRpcUpdateProblemResponse(value: object): value is RpcUpdateProblemResponse {
    if (!('problem' in value) || value['problem'] === undefined) return false;
    return true;
}

export function RpcUpdateProblemResponseFromJSON(json: any): RpcUpdateProblemResponse {
    return RpcUpdateProblemResponseFromJSONTyped(json, false);
}

export function RpcUpdateProblemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateProblemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'problem': RpcProblemFromJSON(json['Problem']),
    };
}

export function RpcUpdateProblemResponseToJSON(json: any): RpcUpdateProblemResponse {
    return RpcUpdateProblemResponseToJSONTyped(json, false);
}

export function RpcUpdateProblemResponseToJSONTyped(value?: RpcUpdateProblemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Problem': RpcProblemToJSON(value['problem']),
    };
}

