/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccountRole } from './RpcAccountRole';
import {
    RpcAccountRoleFromJSON,
    RpcAccountRoleFromJSONTyped,
    RpcAccountRoleToJSON,
    RpcAccountRoleToJSONTyped,
} from './RpcAccountRole';

/**
 * 
 * @export
 * @interface RpcUpdateAccountRequest
 */
export interface RpcUpdateAccountRequest {
    /**
     * 
     * @type {number}
     * @memberof RpcUpdateAccountRequest
     */
    iD: number;
    /**
     * 
     * @type {string}
     * @memberof RpcUpdateAccountRequest
     */
    displayName: string;
    /**
     * 
     * @type {RpcAccountRole}
     * @memberof RpcUpdateAccountRequest
     */
    role: RpcAccountRole;
}



/**
 * Check if a given object implements the RpcUpdateAccountRequest interface.
 */
export function instanceOfRpcUpdateAccountRequest(value: object): value is RpcUpdateAccountRequest {
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    return true;
}

export function RpcUpdateAccountRequestFromJSON(json: any): RpcUpdateAccountRequest {
    return RpcUpdateAccountRequestFromJSONTyped(json, false);
}

export function RpcUpdateAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'displayName': json['DisplayName'],
        'role': RpcAccountRoleFromJSON(json['Role']),
    };
}

export function RpcUpdateAccountRequestToJSON(json: any): RpcUpdateAccountRequest {
    return RpcUpdateAccountRequestToJSONTyped(json, false);
}

export function RpcUpdateAccountRequestToJSONTyped(value?: RpcUpdateAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ID': value['iD'],
        'DisplayName': value['displayName'],
        'Role': RpcAccountRoleToJSON(value['role']),
    };
}

