/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcAccount } from './RpcAccount';
import {
    RpcAccountFromJSON,
    RpcAccountFromJSONTyped,
    RpcAccountToJSON,
    RpcAccountToJSONTyped,
} from './RpcAccount';

/**
 * 
 * @export
 * @interface RpcUpdateAccountResponse
 */
export interface RpcUpdateAccountResponse {
    /**
     * 
     * @type {RpcAccount}
     * @memberof RpcUpdateAccountResponse
     */
    account: RpcAccount;
}

/**
 * Check if a given object implements the RpcUpdateAccountResponse interface.
 */
export function instanceOfRpcUpdateAccountResponse(value: object): value is RpcUpdateAccountResponse {
    if (!('account' in value) || value['account'] === undefined) return false;
    return true;
}

export function RpcUpdateAccountResponseFromJSON(json: any): RpcUpdateAccountResponse {
    return RpcUpdateAccountResponseFromJSONTyped(json, false);
}

export function RpcUpdateAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': RpcAccountFromJSON(json['Account']),
    };
}

export function RpcUpdateAccountResponseToJSON(json: any): RpcUpdateAccountResponse {
    return RpcUpdateAccountResponseToJSONTyped(json, false);
}

export function RpcUpdateAccountResponseToJSONTyped(value?: RpcUpdateAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Account': RpcAccountToJSON(value['account']),
    };
}

