/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - 
 * * `problem_setter` - 
 * * `contestant` - 
 * @export
 */
export const RpcUserRole = {
    Admin: 'admin',
    ProblemSetter: 'problem_setter',
    Contestant: 'contestant'
} as const;
export type RpcUserRole = typeof RpcUserRole[keyof typeof RpcUserRole];


export function instanceOfRpcUserRole(value: any): boolean {
    for (const key in RpcUserRole) {
        if (Object.prototype.hasOwnProperty.call(RpcUserRole, key)) {
            if (RpcUserRole[key as keyof typeof RpcUserRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RpcUserRoleFromJSON(json: any): RpcUserRole {
    return RpcUserRoleFromJSONTyped(json, false);
}

export function RpcUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUserRole {
    return json as RpcUserRole;
}

export function RpcUserRoleToJSON(value?: RpcUserRole | null): any {
    return value as any;
}

export function RpcUserRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): RpcUserRole {
    return value as RpcUserRole;
}

