/* tslint:disable */
/* eslint-disable */
/**
 * API
 * Generated by genpjrpc: v0.5.0
 *
 * The version of the OpenAPI document: v0.0.0-unknown
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RpcTestCase } from './RpcTestCase';
import {
    RpcTestCaseFromJSON,
    RpcTestCaseFromJSONTyped,
    RpcTestCaseToJSON,
    RpcTestCaseToJSONTyped,
} from './RpcTestCase';

/**
 * 
 * @export
 * @interface RpcUpdateTestCaseResponse
 */
export interface RpcUpdateTestCaseResponse {
    /**
     * 
     * @type {RpcTestCase}
     * @memberof RpcUpdateTestCaseResponse
     */
    testCase: RpcTestCase;
}

/**
 * Check if a given object implements the RpcUpdateTestCaseResponse interface.
 */
export function instanceOfRpcUpdateTestCaseResponse(value: object): value is RpcUpdateTestCaseResponse {
    if (!('testCase' in value) || value['testCase'] === undefined) return false;
    return true;
}

export function RpcUpdateTestCaseResponseFromJSON(json: any): RpcUpdateTestCaseResponse {
    return RpcUpdateTestCaseResponseFromJSONTyped(json, false);
}

export function RpcUpdateTestCaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RpcUpdateTestCaseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'testCase': RpcTestCaseFromJSON(json['TestCase']),
    };
}

export function RpcUpdateTestCaseResponseToJSON(json: any): RpcUpdateTestCaseResponse {
    return RpcUpdateTestCaseResponseToJSONTyped(json, false);
}

export function RpcUpdateTestCaseResponseToJSONTyped(value?: RpcUpdateTestCaseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'TestCase': RpcTestCaseToJSON(value['testCase']),
    };
}

