// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wiring

import (
	"clone-carto/internal/app"
	"clone-carto/internal/dataaccess"
	"clone-carto/internal/handlers"
	"clone-carto/internal/handlers/http"
	"clone-carto/internal/handlers/logic"
	"clone-carto/internal/handlers/utils"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeCarto() (app.Carto, func(), error) {
	apiServer := http.NewAPIServerHandler()
	handler := http.NewSPAHandler()
	server := http.NewServer(apiServer, handler)
	logger, cleanup, err := utils.InitializeLogger()
	if err != nil {
		return nil, nil, err
	}
	carto := app.NewCarto(server, logger)
	return carto, func() {
		cleanup()
	}, nil
}

// wire.go:

var WireSet = wire.NewSet(utils.WireSet, dataaccess.WireSet, logic.WireSet, handlers.WireSet, app.WireSet)
